#!/usr/bin/env python3
"""
Download GPM IMERG V07 half-hourly rainfall for 2025 flood season via GEE.

Period: Jul 25 – Aug 31, 2025 (38 days, 1824 half-hourly timesteps)
Regrids from IMERG 0.1 deg lat/lon to v10 30m UTM grid (nearest-neighbour).
Writes one NETCDF3_CLASSIC file per timestep.

Output: v10/input/rain/imerg_v10_t{n}.nc  (n = 1 … 1824)

Usage:
    micromamba run -n zarrv3 python download_imerg_v10.py
"""

import json
import logging
import time
from pathlib import Path

import netCDF4
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# -- Config -------------------------------------------------------------------

SA_KEY = (
    "/data/08-2023/working_notes_jupyter/ignore_nka_gitrepos/"
    "cno-e4drr/devops/earth-engine-service-account/keys/"
    "earthengine-sa-20260130-key.json"
)

# GEE region — wider than domain to ensure full coverage
LAT_MIN, LAT_MAX = 19.3, 19.7
LON_MIN, LON_MAX = 33.1, 33.5

START_DATE = "2025-07-25"
END_DATE   = "2025-09-01"   # exclusive -> Jul 25 – Aug 31

GEE_COLLECTION = "NASA/GPM_L3/IMERG_V07"
GEE_BAND       = "precipitation"
GEE_SCALE_M    = 11132                  # ~0.1 deg at equator

# RIM2D grid (read from v10 dem.nc)
WORK_DIR = Path("/data/rim2d/nile_highres")
V10_DIR  = WORK_DIR / "v10"
DEM_NC   = V10_DIR / "input" / "dem.nc"
CRS_UTM  = "EPSG:32636"

# Output
RAIN_DIR    = V10_DIR / "input" / "rain"
RAIN_PREFIX = "imerg_v10_t"


# -- Write RIM2D NetCDF -------------------------------------------------------

def write_rim2d_nc(data, x, y, nc_path, fill_value=-9999.0):
    """Write a 2-D array to NETCDF3_CLASSIC matching RIM2D expectations."""
    arr = np.where(np.isnan(data), fill_value, data).astype(np.float32)
    nrows, ncols = arr.shape

    ds = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history = "Generated by download_imerg_v10.py"

    ds.createDimension("x", ncols)
    ds.createDimension("y", nrows)

    xv = ds.createVariable("x", "f8", ("x",))
    xv[:] = x
    xv.long_name = "x coordinate"
    xv.units = "m"

    yv = ds.createVariable("y", "f8", ("y",))
    yv[:] = y
    yv.long_name = "y coordinate"
    yv.units = "m"

    bv = ds.createVariable("Band1", "f4", ("y", "x"),
                            fill_value=np.float32(fill_value))
    bv[:] = arr
    bv.long_name = "precipitation rate"
    bv.units = "mm hr-1"

    ds.close()


# -- GEE helpers ---------------------------------------------------------------

def init_ee():
    import ee
    with open(SA_KEY) as f:
        key = json.load(f)
    creds = ee.ServiceAccountCredentials(key["client_email"], SA_KEY)
    ee.Initialize(credentials=creds)
    logger.info(f"EE initialized: {key['client_email']}")
    return ee


def fetch_imerg_getregion(ee):
    """Fetch IMERG half-hourly precipitation via getRegion()."""
    bbox_ee = ee.Geometry.Rectangle([LON_MIN, LAT_MIN, LON_MAX, LAT_MAX])

    col = (
        ee.ImageCollection(GEE_COLLECTION)
        .filterDate(START_DATE, END_DATE)
        .filterBounds(bbox_ee)
        .select(GEE_BAND)
    )

    n = col.size().getInfo()
    logger.info(f"  IMERG images in collection: {n}")
    if n == 0:
        raise RuntimeError(
            f"No images found in {GEE_COLLECTION} for {START_DATE}-{END_DATE}"
        )

    logger.info("  Calling getRegion() — server-side spatial subset...")
    raw = col.getRegion(bbox_ee, scale=GEE_SCALE_M).getInfo()
    logger.info(f"  getRegion: {len(raw)-1} pixel-timestep records returned")
    return raw


def parse_getregion(raw):
    """Parse getRegion output into structured numpy arrays."""
    import pandas as pd

    header = raw[0]
    rows = raw[1:]

    lon_idx  = header.index("longitude")
    lat_idx  = header.index("latitude")
    time_idx = header.index("time")
    val_idx  = header.index(GEE_BAND)

    lons = np.array([r[lon_idx] for r in rows], dtype=np.float64)
    lats = np.array([r[lat_idx] for r in rows], dtype=np.float64)
    times_ms = np.array([r[time_idx] for r in rows], dtype=np.int64)
    vals = np.array(
        [r[val_idx] if r[val_idx] is not None else np.nan for r in rows],
        dtype=np.float32,
    )

    lons = np.round(lons, 5)
    lats = np.round(lats, 5)

    times_dt = pd.to_datetime(times_ms, unit="ms").values.astype("datetime64[ns]")
    times_uniq = np.sort(np.unique(times_dt))
    lats_uniq = np.sort(np.unique(lats))
    lons_uniq = np.sort(np.unique(lons))

    n_t = len(times_uniq)
    n_lat = len(lats_uniq)
    n_lon = len(lons_uniq)

    t_idx = np.searchsorted(times_uniq, times_dt)
    lat_idx2 = np.searchsorted(lats_uniq, lats)
    lon_idx2 = np.searchsorted(lons_uniq, lons)

    data_3d = np.full((n_t, n_lat, n_lon), np.nan, dtype=np.float32)
    data_3d[t_idx, lat_idx2, lon_idx2] = vals

    logger.info(f"  IMERG grid: {n_t} timesteps x {n_lat} lat x {n_lon} lon")
    logger.info(f"  IMERG lat:  {lats_uniq[0]:.4f} ... {lats_uniq[-1]:.4f}")
    logger.info(f"  IMERG lon:  {lons_uniq[0]:.4f} ... {lons_uniq[-1]:.4f}")
    valid = np.sum(np.isfinite(data_3d))
    logger.info(f"  Valid values: {valid}/{data_3d.size} "
                f"({100*valid/data_3d.size:.1f}%)")

    return times_uniq, lats_uniq, lons_uniq, data_3d


# -- Main ---------------------------------------------------------------------

def main():
    import pandas as pd

    logger.info("=" * 60)
    logger.info("v10: GPM IMERG 2025 -> RIM2D rain files")
    logger.info(f"  Collection: {GEE_COLLECTION}")
    logger.info(f"  Band:       {GEE_BAND}")
    logger.info(f"  Region:     lat [{LAT_MIN},{LAT_MAX}] lon [{LON_MIN},{LON_MAX}]")
    logger.info(f"  Period:     {START_DATE} -> {END_DATE}")
    logger.info(f"  Output:     {RAIN_DIR}")
    logger.info("=" * 60)
    t0 = time.time()

    # Read RIM2D grid from v10 dem.nc
    logger.info(f"Reading RIM2D grid from {DEM_NC}...")
    ds_dem = netCDF4.Dataset(str(DEM_NC))
    rim2d_x = ds_dem["x"][:].data.copy()
    rim2d_y = ds_dem["y"][:].data.copy()
    ds_dem.close()
    nrows, ncols = len(rim2d_y), len(rim2d_x)
    logger.info(f"  RIM2D grid: {ncols} x {nrows} cells at ~30m")

    # Fetch IMERG via GEE getRegion
    ee = init_ee()
    raw = fetch_imerg_getregion(ee)

    # Parse into 3-D array
    logger.info("Parsing getRegion output...")
    times_uniq, imerg_lats, imerg_lons, data_3d = parse_getregion(raw)
    del raw

    n_times = len(times_uniq)
    logger.info(f"  Time range: {times_uniq[0]} -> {times_uniq[-1]}")

    # Pre-compute UTM -> lat/lon mapping
    logger.info("Pre-computing UTM -> lat/lon for RIM2D grid...")
    from pyproj import Transformer
    transformer = Transformer.from_crs(CRS_UTM, "EPSG:4326", always_xy=True)
    xx, yy = np.meshgrid(rim2d_x, rim2d_y)
    rim_lons_flat, rim_lats_flat = transformer.transform(
        xx.ravel(), yy.ravel()
    )
    # Nearest-neighbour indices (static)
    lat_nn = np.argmin(
        np.abs(imerg_lats[:, None] - rim_lats_flat[None, :]), axis=0
    )
    lon_nn = np.argmin(
        np.abs(imerg_lons[:, None] - rim_lons_flat[None, :]), axis=0
    )

    # Write one NetCDF per timestep
    RAIN_DIR.mkdir(parents=True, exist_ok=True)
    logger.info(f"Writing {n_times} NetCDF rain files to {RAIN_DIR}...")

    rain_vals_all = []
    for i, t in enumerate(times_uniq):
        imerg_frame = data_3d[i]

        out_flat = imerg_frame[lat_nn, lon_nn]
        out_flat = np.where(np.isfinite(out_flat) & (out_flat >= 0), out_flat, 0.0)
        rain_2d = out_flat.reshape(nrows, ncols).astype(np.float32)

        nc_path = RAIN_DIR / f"{RAIN_PREFIX}{i+1}.nc"
        write_rim2d_nc(rain_2d, rim2d_x, rim2d_y, nc_path)

        mean_val = float(np.mean(rain_2d))
        rain_vals_all.append(mean_val)
        if (i + 1) % 48 == 0 or i == 0 or i == n_times - 1:
            dt_str = str(pd.Timestamp(t))[:16]
            logger.info(f"  [{i+1:4d}/{n_times}] {dt_str}  "
                        f"mean={mean_val:.3f} mm/hr  -> {nc_path.name}")

    # Summary
    elapsed = time.time() - t0
    rain_arr = np.array(rain_vals_all)
    logger.info("=" * 60)
    logger.info("DONE")
    logger.info(f"  Files written: {n_times}")
    logger.info(f"  Prefix:        {RAIN_PREFIX}1.nc ... {RAIN_PREFIX}{n_times}.nc")
    logger.info(f"  Rain stats:    mean={rain_arr.mean():.4f}  "
                f"max={rain_arr.max():.4f}  min={rain_arr.min():.4f} mm/hr")
    logger.info(f"  RIM2D grid:    {ncols}x{nrows} cells")
    logger.info(f"  Elapsed:       {elapsed:.1f}s")
    logger.info("")
    logger.info("To use in simulation_v10.def:")
    logger.info(f"  **pluvial_raster_nr**")
    logger.info(f"  {n_times}")
    logger.info(f"  **pluvial_dt**")
    logger.info(f"  1800")
    logger.info(f"  **pluvial_base_fn**")
    logger.info(f"  input/rain/{RAIN_PREFIX}")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
