#!/usr/bin/env python3
"""
v1 Synthetic Hydrograph from Basin-Derived Catchment Rainfall — Nairobi.

Improvement over run_v1_river_inflow.py:
  - Catchment areas from HydroATLAS (delineate_watershed_v1.py) instead of
    flow-accumulation pixel counts
  - IMERG rainfall downloaded over the FULL BASIN extent (not just simulation
    domain) — captures upstream Nairobi/Athi highlands rainfall
  - Rational method + triangular UH with empirical tc from basin area
  - Runoff coefficient appropriate for tropical urban catchments

Also fixes the channel mask: replaces sparse ESA WorldCover class-80 mask
with a flow-accumulation-based river network (flwacc >= ACC_CHANNEL_THRESH).

Usage:
    cd /data/rim2d/nbo_2026
    # Step 1: delineate watersheds first (if not done)
    micromamba run -n zarrv3 python delineate_watershed_v1.py

    # Step 2: this script
    micromamba run -n zarrv3 python run_v1_synthetic_flood.py
"""

import json
import logging
import time
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import netCDF4
import numpy as np
from pyproj import Transformer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# -- Paths --------------------------------------------------------------------
WORK_DIR  = Path(__file__).parent        # /data/rim2d/nbo_2026
V1_DIR    = WORK_DIR / "v1"
INPUT_DIR = V1_DIR / "input"
WS_DIR    = INPUT_DIR / "watersheds"
RAIN_DIR  = INPUT_DIR / "rain"
VIS_DIR   = V1_DIR / "visualizations"

SA_KEY = (
    "/data/08-2023/working_notes_jupyter/ignore_nka_gitrepos/"
    "cno-e4drr/devops/earth-engine-service-account/keys/"
    "earthengine-sa-20260130-key.json"
)

CRS_UTM = "EPSG:32737"

# -- Simulation timing --------------------------------------------------------
SIM_DUR   = 2592000   # 30 days
DT_INFLOW = 1800      # 30-min boundary timestep
N_RAIN    = 1440      # 30 days × 48
N_WSE     = SIM_DUR // DT_INFLOW + 1  # 1441

# -- IMERG config (April 2025 Nairobi long rains) ----------------------------
GEE_COLLECTION = "NASA/GPM_L3/IMERG_V07"
GEE_BAND       = "precipitation"
START_DATE     = "2025-04-01"
END_DATE       = "2025-05-01"   # exclusive

# -- Channel hydraulics for natural tropical rivers ---------------------------
CHANNEL_WIDTH  = 20.0    # m — typical Nairobi river
CHANNEL_SLOPE  = 0.003   # m/m
N_MANNING_CH   = 0.040   # natural channel

# -- Runoff parameters --------------------------------------------------------
# Base runoff coefficient for urban tropical catchment.
# Will be calibrated against observed flood impacts if needed.
RUNOFF_COEFF   = 0.55    # tropical urban mixed (can range 0.4–0.85)
MAX_Q_ENTRY    = 2000.0  # m3/s hard cap per entry

# -- Channel mask fix ---------------------------------------------------------
# Replace sparse ESA WorldCover class-80 mask with flow-accumulation network.
# Cells with flwacc >= this threshold are treated as river channel.
ACC_CHANNEL_THRESH = 5000   # upstream cells (~4.5 km2 minimum drainage area)
CHANNEL_FILL_VALUE = 3.0    # IWD depth (m) at channel cells

# -- HydroATLAS level preference ----------------------------------------------
LEVEL_PREFERENCE = ["12", "10", "8", "6", "4"]


# -- Helpers ------------------------------------------------------------------

def load_nc(path):
    ds      = netCDF4.Dataset(str(path))
    x       = ds["x"][:]
    y       = ds["y"][:]
    varname = [v for v in ds.variables if v not in ("x", "y")][0]
    data    = np.array(ds[varname][:], dtype=np.float64)
    ds.close()
    data[data < -9000] = np.nan
    return data, x, y


def write_rim2d_nc(data, x, y, nc_path, fill_value=-9999.0):
    arr   = np.where(np.isnan(data), fill_value, data).astype(np.float32)
    nrows, ncols = arr.shape
    ds    = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history     = "Generated by run_v1_synthetic_flood.py"
    ds.createDimension("x", ncols);  ds.createDimension("y", nrows)
    xv  = ds.createVariable("x", "f8", ("x",)); xv[:] = x
    yv  = ds.createVariable("y", "f8", ("y",)); yv[:] = y
    bv  = ds.createVariable("Band1", "f4", ("y", "x"),
                            fill_value=np.float32(fill_value))
    bv[:] = arr
    ds.close()


def latlon_to_grid(lat, lon, x, y):
    to_utm = Transformer.from_crs("EPSG:4326", CRS_UTM, always_xy=True)
    utm_x, utm_y = to_utm.transform(lon, lat)
    col = int(np.argmin(np.abs(x - utm_x)))
    row = int(np.argmin(np.abs(y - utm_y)))
    return row, col


# -- Channel mask fix ---------------------------------------------------------

def fix_channel_mask():
    """
    Replace sparse class-80 channel mask with flow-accumulation-based mask.
    Also rebuilds dem.nc (stream-burned) and iwd.nc from the new channel mask.
    """
    logger.info("\n--- Fixing channel mask (flow-accumulation based) ---")

    # Load raw (un-burned) DEM from GeoTIFF
    import rasterio
    dem_tif = V1_DIR / "tif" / "dem.tif"
    with rasterio.open(str(dem_tif)) as src:
        raw_dem_arr = src.read(1).astype(np.float64)
        nodata      = src.nodata

    # Load existing x/y from dem.nc
    ds_ref = netCDF4.Dataset(str(INPUT_DIR / "dem.nc"))
    x      = ds_ref["x"][:].data.copy()
    y      = ds_ref["y"][:].data.copy()
    ds_ref.close()

    # Reconstruct raw DEM in RIM2D y-ascending convention
    raw_dem = raw_dem_arr[::-1, :].copy()
    if nodata is not None:
        raw_dem[np.isclose(raw_dem, nodata)] = np.nan
    raw_dem[~np.isfinite(raw_dem)] = np.nan

    # Load flow accumulation
    flwacc, _, _ = load_nc(INPUT_DIR / "flwacc_30m.nc")
    nrows, ncols = flwacc.shape

    # New channel mask: cells with high flow accumulation
    channel_mask = (flwacc >= ACC_CHANNEL_THRESH).astype(np.float32)
    channel_mask[np.isnan(flwacc)] = 0.0

    n_channel = int(np.sum(channel_mask))
    logger.info(f"  Flow-acc channel cells (>={ACC_CHANNEL_THRESH}): "
                f"{n_channel} ({100*n_channel/flwacc.size:.1f}%)")

    # Write new channel mask
    write_rim2d_nc(channel_mask, x, y, INPUT_DIR / "channel_mask.nc")
    logger.info("  Written: channel_mask.nc (updated)")

    # Rebuild burned DEM
    burned_dem = raw_dem.copy()
    burned_dem[channel_mask > 0] -= CHANNEL_FILL_VALUE
    write_rim2d_nc(burned_dem, x, y, INPUT_DIR / "dem.nc")
    logger.info("  Written: dem.nc (re-burned from raw DEM)")

    # Rebuild IWD
    iwd = np.where(channel_mask > 0, CHANNEL_FILL_VALUE, 0.0)
    write_rim2d_nc(iwd, x, y, INPUT_DIR / "iwd.nc")
    logger.info("  Written: iwd.nc (updated)")

    return channel_mask, x, y, burned_dem


# -- Watershed loading --------------------------------------------------------

def load_watershed_summary():
    path = WS_DIR / "watershed_summary.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Not found: {path}\nRun: python delineate_watershed_v1.py first."
        )
    with open(str(path)) as f:
        return json.load(f)


def get_best_area(ws_summary, entry_name):
    """Return best catchment area (km2) from finest available HydroATLAS level."""
    entry = ws_summary.get(entry_name, {})
    levels = entry.get("levels", {})

    for level in LEVEL_PREFERENCE:
        if level in levels and levels[level]:
            sub = levels[level].get("sub_area_km2")
            up  = levels[level].get("up_area_km2")
            # Use UP_AREA (total upstream) if SUB_AREA seems too small
            # (SUB_AREA is only the sub-basin; UP_AREA is total upstream drainage)
            if sub and sub > 1.0:
                return float(sub), int(level), "SUB_AREA"
            elif up and up > 1.0:
                return float(up), int(level), "UP_AREA"

    # Fallback: use flow-accumulation estimate
    km2 = entry.get("km2_flwacc", 50.0)
    logger.warning(f"  {entry_name}: no HydroATLAS area — using flow_acc estimate "
                   f"({km2:.1f} km2)")
    return km2, 0, "flow_acc"


def get_basin_polygon(ws_summary, entry_name):
    """Return (bbox, geom_dict) for the best available basin level."""
    entry  = ws_summary.get(entry_name, {})
    levels = entry.get("levels", {})

    for level in LEVEL_PREFERENCE:
        if level not in levels or not levels[level]:
            continue
        geojson_path = WS_DIR / f"{entry_name}_level{int(level):02d}.geojson"
        if not geojson_path.exists():
            continue
        with open(str(geojson_path)) as f:
            fc   = json.load(f)
        geom = fc["features"][0]["geometry"]

        coords = []
        if geom["type"] == "Polygon":
            coords = geom["coordinates"][0]
        elif geom["type"] == "MultiPolygon":
            for poly in geom["coordinates"]:
                coords.extend(poly[0])

        lons   = [c[0] for c in coords]
        lats   = [c[1] for c in coords]
        bbox   = {"west": min(lons), "east": max(lons),
                  "south": min(lats), "north": max(lats)}
        return bbox, geom, int(level)

    return None, None, None


# -- IMERG basin-scale rainfall -----------------------------------------------

def init_ee():
    import ee
    with open(SA_KEY) as f:
        key = json.load(f)
    creds = ee.ServiceAccountCredentials(key["client_email"], SA_KEY)
    ee.Initialize(credentials=creds)
    logger.info(f"EE initialized: {key['client_email']}")
    return ee


def download_basin_rainfall(ee, basin_bbox, basin_geom=None):
    """Download IMERG basin-mean rainfall time series via GEE reduceRegion."""
    import pandas as pd

    bbox_ee = ee.Geometry.Rectangle([
        basin_bbox["west"]  - 0.05,
        basin_bbox["south"] - 0.05,
        basin_bbox["east"]  + 0.05,
        basin_bbox["north"] + 0.05,
    ])
    region = ee.Geometry(basin_geom) if basin_geom else bbox_ee

    col = (
        ee.ImageCollection(GEE_COLLECTION)
        .filterDate(START_DATE, END_DATE)
        .filterBounds(bbox_ee)
        .select(GEE_BAND)
    )
    n = col.size().getInfo()
    logger.info(f"    IMERG images over basin: {n}")
    if n == 0:
        raise RuntimeError("No IMERG images found for basin")

    def compute_mean(image):
        val = image.reduceRegion(
            reducer=ee.Reducer.mean(),
            geometry=region,
            scale=11132,
            maxPixels=1e8,
        )
        return image.set("basin_mean", val.get(GEE_BAND))

    col_m      = col.map(compute_mean)
    rain_list  = col_m.aggregate_array("basin_mean").getInfo()
    time_list  = col_m.aggregate_array("system:time_start").getInfo()

    times_ms   = np.array(time_list, dtype=np.int64)
    rain_vals  = np.array(
        [v if v is not None else 0.0 for v in rain_list], dtype=np.float64
    )
    idx        = np.argsort(times_ms)
    times_ms   = times_ms[idx];  rain_vals = rain_vals[idx]
    times_dt   = pd.to_datetime(times_ms, unit="ms").values.astype("datetime64[ns]")

    total_mm   = np.sum(rain_vals) * 0.5
    logger.info(f"    Basin-mean total: {total_mm:.1f} mm | "
                f"peak: {rain_vals.max():.2f} mm/hr | "
                f"wet: {int(np.sum(rain_vals>0.1))}/{len(rain_vals)}")
    return times_dt, rain_vals


def read_domain_rain():
    """Domain-mean rain from downloaded rain files (fallback if no basin IMERG)."""
    rates = np.zeros(N_RAIN)
    n_found = 0
    for t in range(1, N_RAIN + 1):
        p = RAIN_DIR / f"imerg_v1_t{t}.nc"
        if not p.exists():
            continue
        ds   = netCDF4.Dataset(str(p))
        data = np.array(ds["Band1"][:], dtype=np.float32)
        ds.close()
        data[data < -9000] = 0.0;  data[~np.isfinite(data)] = 0.0
        rates[t - 1] = float(np.mean(data));  n_found += 1
    logger.info(f"  Domain rain files loaded: {n_found}/{N_RAIN}, "
                f"total={np.sum(rates)*0.5:.1f} mm")
    return rates


# -- Hydrograph computation ---------------------------------------------------

def compute_tc(area_km2):
    """Time of concentration (hours) from catchment area. tc = 0.3 * A^0.4."""
    tc = 0.3 * area_km2**0.4
    return float(np.clip(tc, 1.0, 24.0))


def make_uh(tc_hours, dt_s):
    tc_s = tc_hours * 3600.0
    tb   = 2.0 * tc_s
    n    = int(np.ceil(tb / dt_s)) + 1
    t    = np.arange(n) * dt_s
    uh   = np.where(t <= tc_s, t / tc_s,
                    np.where(t <= tb, (tb - t) / tc_s, 0.0))
    uh[uh < 0] = 0.0
    return uh / uh.sum()


def compute_hydrograph(rain_mmhr, area_m2, uh):
    rain_ms   = rain_mmhr / (1000.0 * 3600.0)
    q_instant = RUNOFF_COEFF * rain_ms * area_m2
    q_conv    = np.convolve(q_instant, uh, mode="full")[:len(rain_mmhr)]
    return np.clip(q_conv, 0.0, MAX_Q_ENTRY)


def flow_to_wse(q, dem_elev):
    """Manning's wide rectangular channel: depth = (Q*n / (w*S^0.5))^(3/5)."""
    if q <= 0.0:
        return dem_elev
    w     = CHANNEL_WIDTH;  n = N_MANNING_CH;  s = CHANNEL_SLOPE
    depth = (q * n / (w * s**0.5))**(3.0 / 5.0)
    return dem_elev + min(depth, 20.0)


# -- Output writers -----------------------------------------------------------

def write_boundary_mask(entries_with_rowcol, dem, x, y, out_path):
    nrows, ncols = dem.shape
    mask = np.zeros((nrows, ncols), dtype=np.float32)
    for i, (row, col, _) in enumerate(entries_with_rowcol):
        mask[row, col] = float(i + 1)
    write_rim2d_nc(mask, x, y, out_path)
    logger.info(f"  Written: {out_path.name} ({int(mask.max())} zones)")


def write_inflowlocs(entries_with_rowcol, wse_ts, out_path):
    n = len(entries_with_rowcol)
    with open(str(out_path), "w") as f:
        f.write(f"{SIM_DUR}\n{DT_INFLOW}\n{n}\n")
        for i, (row, col, _) in enumerate(entries_with_rowcol):
            vals = [str(row + 1), str(col + 1)]
            vals.extend(f"{v:.3f}" for v in wse_ts[i])
            f.write("\t".join(vals) + "\n")
    logger.info(f"  Written: {out_path.name} ({n} cells, {N_WSE} WSE each)")


def plot_hydrographs(q_dict, rain_dict, entries_meta, out_path):
    """Plot per-entry hydrographs and basin-mean rainfall."""
    n_entries = len(q_dict)
    times_h   = np.arange(N_WSE) * DT_INFLOW / 3600.0
    days      = times_h / 24.0

    colors = plt.cm.tab10(np.linspace(0, 0.9, max(n_entries, 1)))

    fig, axes = plt.subplots(2, 1, figsize=(14, 10))

    for i, (name, q) in enumerate(q_dict.items()):
        meta = entries_meta.get(name, {})
        area = meta.get("area_km2", 0)
        peak = q.max()
        axes[0].plot(days, q, color=colors[i], linewidth=1.5,
                     label=f"{name} ({area:.0f} km², peak={peak:.0f} m³/s)")

    axes[0].set_xlabel("Days from Apr 1 2025")
    axes[0].set_ylabel("Flow (m³/s)")
    axes[0].set_title(
        f"River Entry Hydrographs — {n_entries} entries (C={RUNOFF_COEFF})",
        fontsize=12, fontweight="bold"
    )
    axes[0].legend(fontsize=8, ncol=2)
    axes[0].grid(alpha=0.3)

    # Domain-mean + basin-mean rain comparison
    for name, rain in rain_dict.items():
        if rain is None:
            continue
        rain_days = np.arange(len(rain)) * 0.5 / 24.0
        axes[1].plot(rain_days, rain, linewidth=0.8, alpha=0.6, label=name)

    axes[1].set_xlabel("Days from Apr 1 2025")
    axes[1].set_ylabel("Rain rate (mm/hr)")
    axes[1].set_title("Basin-Mean & Domain-Mean IMERG Rainfall",
                      fontsize=12, fontweight="bold")
    axes[1].legend(fontsize=7, ncol=3)
    axes[1].grid(alpha=0.3)

    fig.suptitle("Nairobi v1 — Synthetic Hydrograph (HydroATLAS + Basin IMERG)",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    fig.savefig(str(out_path), dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    logger.info(f"  Saved: {out_path.name}")


# -- Main ---------------------------------------------------------------------

def main():
    t0 = time.time()
    logger.info("=" * 70)
    logger.info("Nairobi v1 — Synthetic Hydrograph (HydroATLAS + Basin IMERG)")
    logger.info("=" * 70)

    VIS_DIR.mkdir(parents=True, exist_ok=True)

    # Step 1: Fix channel mask
    channel_mask, x, y, dem = fix_channel_mask()

    # Step 2: Load watershed summary
    logger.info("\n--- Loading HydroATLAS watershed areas ---")
    ws_summary = load_watershed_summary()
    entry_names = list(ws_summary.keys())
    logger.info(f"  Entries in summary: {len(entry_names)}")

    # Step 3: Map entry lat/lon back to grid row/col
    logger.info("\n--- Mapping entry points to grid ---")
    entries_with_rowcol = []
    entries_meta        = {}

    for name in entry_names:
        info = ws_summary[name]
        lat  = info["lat"];  lon = info["lon"]
        row, col = latlon_to_grid(lat, lon, x, y)
        area_km2, level, area_src = get_best_area(ws_summary, name)
        elev = float(dem[row, col]) if np.isfinite(dem[row, col]) else 0.0

        entries_with_rowcol.append((row, col, name))
        entries_meta[name] = {
            "lat": lat, "lon": lon, "row": row, "col": col,
            "area_km2": area_km2, "hydroatlas_level": level,
            "area_source": area_src, "elevation_m": elev,
        }
        logger.info(f"  {name}: row={row}, col={col}, "
                    f"area={area_km2:.1f} km2 (L{level} {area_src}), "
                    f"elev={elev:.1f}m")

    # Step 4: Download basin-scale IMERG
    logger.info("\n--- Downloading basin-scale IMERG rainfall ---")
    ee     = init_ee()
    domain_rain = read_domain_rain()
    basin_rain  = {}

    for name in entry_names:
        logger.info(f"\n  {name}...")
        bbox, geom, level = get_basin_polygon(ws_summary, name)
        if bbox is None:
            logger.warning(f"  No basin polygon — using domain-mean rainfall")
            basin_rain[name] = domain_rain.copy()
            continue

        span_lon = bbox["east"]  - bbox["west"]
        span_lat = bbox["north"] - bbox["south"]
        logger.info(f"    Basin bbox: {span_lon:.2f}° lon × {span_lat:.2f}° lat "
                    f"(level {level})")
        try:
            _, rain = download_basin_rainfall(ee, bbox, geom)
            # Pad / trim to N_RAIN
            padded = np.zeros(N_RAIN)
            n_copy = min(len(rain), N_RAIN)
            padded[:n_copy] = rain[:n_copy]
            basin_rain[name] = padded
        except Exception as exc:
            logger.warning(f"    IMERG download failed ({exc}) — "
                           "using domain-mean as fallback")
            basin_rain[name] = domain_rain.copy()

    # Step 5: Compute hydrographs
    logger.info("\n--- Computing hydrographs ---")
    q_dict       = {}
    wse_ts_list  = []

    for name in entry_names:
        meta       = entries_meta[name]
        area_km2   = meta["area_km2"]
        area_m2    = area_km2 * 1e6
        elev       = meta["elevation_m"]
        tc         = compute_tc(area_km2)
        uh         = make_uh(tc, DT_INFLOW)
        rain       = basin_rain[name]

        q     = compute_hydrograph(rain, area_m2, uh)
        q_wse = np.zeros(N_WSE)
        n_cp  = min(len(q), N_WSE - 1)
        q_wse[1:n_cp + 1] = q[:n_cp]

        wse = np.array([flow_to_wse(qi, elev) for qi in q_wse])
        wse_ts_list.append(wse)
        q_dict[name] = q_wse

        peak_q     = q_wse.max()
        peak_depth = wse.max() - elev
        vol_m3     = np.sum(q_wse[1:]) * DT_INFLOW
        logger.info(f"  {name}: area={area_km2:.0f} km2, tc={tc:.1f}h, "
                    f"peak={peak_q:.1f} m3/s, depth={peak_depth:.2f}m, "
                    f"vol={vol_m3/1e6:.2f} Mm3")

    # Step 6: Write boundary files
    logger.info("\n--- Writing boundary files ---")
    write_boundary_mask(entries_with_rowcol, dem, x, y,
                        INPUT_DIR / "fluvbound_mask_v1.nc")
    write_inflowlocs(entries_with_rowcol, wse_ts_list,
                     INPUT_DIR / "inflowlocs_v1.txt")

    # Save hydrograph data
    npz_data = {
        "times_h":    np.arange(N_WSE) * DT_INFLOW / 3600.0,
        "domain_rain": domain_rain,
    }
    for name in entry_names:
        npz_data[f"q_{name}"]    = q_dict[name]
        npz_data[f"rain_{name}"] = basin_rain[name]
    np.savez(str(INPUT_DIR / "synthetic_hydrographs.npz"), **npz_data)
    logger.info("  Written: synthetic_hydrographs.npz")

    # Save metadata JSON
    meta_out = {
        "sim_dur": SIM_DUR, "dt_inflow": DT_INFLOW,
        "runoff_coeff": RUNOFF_COEFF,
        "channel_thresh": ACC_CHANNEL_THRESH,
        "entries": entries_meta,
    }
    with open(str(INPUT_DIR / "v1_synthetic_metadata.json"), "w") as f:
        json.dump(meta_out, f, indent=2)
    logger.info("  Written: v1_synthetic_metadata.json")

    # Step 7: Plot hydrographs
    rain_plot = {"domain_mean": domain_rain}
    for name in list(entry_names)[:3]:   # top 3 basins for readability
        rain_plot[name] = basin_rain[name]
    plot_hydrographs(q_dict, rain_plot, entries_meta,
                     VIS_DIR / "v1_synthetic_hydrographs.png")

    # Summary
    elapsed = time.time() - t0
    logger.info("\n" + "=" * 70)
    logger.info("SETUP COMPLETE")
    logger.info(f"  Elapsed: {elapsed:.0f}s")
    logger.info(f"  Channel mask: {int(np.sum(channel_mask))} cells "
                f"({100*np.mean(channel_mask>0):.1f}% of domain)")
    logger.info(f"  River entries: {len(entry_names)}")
    logger.info(f"  Peak flows: " +
                ", ".join(f"{n}={q_dict[n].max():.0f}" for n in entry_names))
    logger.info("\nNext steps:")
    logger.info("  python visualize_v1.py --inputs   (re-run to see updated channel mask)")
    logger.info("  cd v1 && ../../bin/RIM2D simulation_v1.def --def flex")
    logger.info("=" * 70)


if __name__ == "__main__":
    main()
