#!/usr/bin/env python3
"""
Nairobi v3 — Stream-Burn IWD Setup.

Implements the three-step satellite-based IWD method (adapted from Nile v7):

  Step 1 — Extract ESA WorldCover channel mask
           Load raw WorldCover class map (already downloaded in v1).
           Class 80 = permanent water → binary channel_mask.

  Step 2 — Stream-burn the DEM
           Lower DEM by BURN_DEPTH at all channel cells.
           This carves a physically consistent river channel into the terrain.

  Step 3 — Compute IWD from burn depth
           IWD = BURN_DEPTH at channel cells, 0 elsewhere.
           The initial water exactly fills the carved channel back to
           the original surface — a flat, stable initial condition.

All other input rasters (roughness, buildings, sealed/pervious surface,
sewershed) are copied from v1/input unchanged.

Outputs → v3/input/
  channel_mask.nc   binary water mask (class 80)
  dem.nc            stream-burned DEM
  iwd.nc            initial water depth (BURN_DEPTH at channel, 0 elsewhere)
  roughness.nc      Manning's n (copy from v1)
  buildings.nc      building density raster (copy from v1)
  sealed_surface.nc sealed fraction (copy from v1)
  pervious_surface.nc pervious fraction (copy from v1)
  sewershed_v1_full.nc sewershed mask (copy from v1)

Usage:
    cd /data/rim2d/nbo_2026
    micromamba run -n zarrv3 python setup_v3.py
"""

import shutil
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import netCDF4
import numpy as np

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
WORK_DIR  = Path(__file__).resolve().parent
V1_INPUT  = WORK_DIR / "v1" / "input"
V1_TIF    = WORK_DIR / "v1" / "tif"
V3_DIR    = WORK_DIR / "v3"
INPUT_DIR = V3_DIR / "input"
VIS_DIR   = V3_DIR / "visualizations"

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
BURN_DEPTH   = 3.0   # m — depth to carve into DEM at water pixels
NORMAL_DEPTH = 3.0   # m — IWD at channel cells (= BURN_DEPTH → fills channel)

# WorldCover classes to include in channel mask
# 80 = Permanent water bodies (rivers, lakes)
# 90 = Herbaceous wetlands (include to capture riverine wetlands)
WATER_CLASSES = [80]

DPI = 150

# ---------------------------------------------------------------------------
# I/O helpers (mirrors setup_v1.py)
# ---------------------------------------------------------------------------

def tif_to_rim2d_arrays(tif_path):
    import rasterio
    with rasterio.open(str(tif_path)) as src:
        data      = src.read(1).astype(np.float64)
        transform = src.transform
        nodata    = src.nodata
    nrows, ncols = data.shape
    x     = transform.c + transform.a * (np.arange(ncols) + 0.5)
    y_top = transform.f + transform.e * (np.arange(nrows) + 0.5)
    y     = y_top[::-1]
    data  = data[::-1, :].copy()
    if nodata is not None:
        data[np.isclose(data, nodata)] = np.nan
    data[~np.isfinite(data)] = np.nan
    return data, x, y


def write_rim2d_nc(data, x, y, nc_path, varname="Band1"):
    fill = -9999.0
    arr  = np.where(np.isnan(data), fill, data).astype(np.float32)
    nrows, ncols = arr.shape
    ds = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history     = "Generated by setup_v3.py (Nairobi v3)"
    ds.createDimension("x", ncols)
    ds.createDimension("y", nrows)
    xv = ds.createVariable("x", "f8", ("x",))
    xv[:] = x
    xv.long_name = "x coordinate"
    xv.standard_name = "projection_x_coordinate"
    xv.units = "m"
    yv = ds.createVariable("y", "f8", ("y",))
    yv[:] = y
    yv.long_name = "y coordinate"
    yv.standard_name = "projection_y_coordinate"
    yv.units = "m"
    bv = ds.createVariable(varname, "f4", ("y", "x"),
                           fill_value=np.float32(fill))
    bv[:] = arr
    ds.close()


def load_nc(path):
    ds = netCDF4.Dataset(str(path))
    x = np.array(ds["x"][:])
    y = np.array(ds["y"][:])
    varname = [v for v in ds.variables if v not in ("x", "y")][0]
    data = np.array(ds[varname][:], dtype=np.float64)
    ds.close()
    data[data < -9000] = np.nan
    return data, x, y


# ---------------------------------------------------------------------------
# Step 1 — Channel mask from WorldCover
# ---------------------------------------------------------------------------

def step1_channel_mask():
    print("=" * 60)
    print("Step 1 — ESA WorldCover channel mask")
    print("=" * 60)

    wc_path = V1_TIF / "worldcover_classes.tif"
    if not wc_path.exists():
        raise FileNotFoundError(
            f"{wc_path} not found. Run setup_v1.py step 1 first "
            "(or copy worldcover_classes.tif to v1/tif/)."
        )

    wc, x, y = tif_to_rim2d_arrays(wc_path)
    wc_int = np.nan_to_num(wc, nan=0).astype(np.int16)

    # Build channel mask from selected WorldCover classes
    channel_mask = np.zeros_like(wc_int, dtype=np.float32)
    for cls in WATER_CLASSES:
        channel_mask[wc_int == cls] = 1.0

    n_water = int(np.sum(channel_mask > 0))
    print(f"  WorldCover classes used : {WATER_CLASSES}")
    print(f"  Channel mask cells      : {n_water:,}  "
          f"({100 * n_water / channel_mask.size:.2f}% of domain)")

    # Save unique class distribution
    classes, counts = np.unique(wc_int[wc_int > 0], return_counts=True)
    print("  WorldCover class distribution in domain:")
    CLASS_NAMES = {
        10: "Tree cover", 20: "Shrubland", 30: "Grassland",
        40: "Cropland",   50: "Built-up",  60: "Bare/sparse veg",
        70: "Snow/ice",   80: "Perm. water", 90: "Herbaceous wetland",
        95: "Mangroves",  100: "Moss/lichen",
    }
    for c, cnt in zip(classes, counts):
        flag = " ← channel" if c in WATER_CLASSES else ""
        name = CLASS_NAMES.get(int(c), "Unknown")
        print(f"    Class {c:3d} ({name}): {cnt:7,} cells{flag}")

    return channel_mask, wc_int, x, y


# ---------------------------------------------------------------------------
# Step 2 — Stream-burn DEM
# ---------------------------------------------------------------------------

def step2_burn_dem(channel_mask, x, y):
    print()
    print("=" * 60)
    print("Step 2 — Stream-burn DEM")
    print("=" * 60)

    dem_path = V1_INPUT / "dem.nc"
    # Load the original (un-burned) DEM — v1 dem.nc is already burned.
    # Use the source tif for the original surface.
    original_dem, _, _ = tif_to_rim2d_arrays(V1_TIF / "dem.tif")

    n_ch = int(np.sum(channel_mask > 0))
    burned_dem = original_dem.copy()
    burned_dem[channel_mask > 0] -= BURN_DEPTH

    burn_actual = original_dem[channel_mask > 0] - burned_dem[channel_mask > 0]
    print(f"  Original DEM  : {np.nanmin(original_dem):.1f} – "
          f"{np.nanmax(original_dem):.1f} m")
    print(f"  Burn depth    : uniform {BURN_DEPTH} m at {n_ch:,} channel cells")
    print(f"  Burned DEM min: {np.nanmin(burned_dem):.1f} m")

    return original_dem, burned_dem, x, y


# ---------------------------------------------------------------------------
# Step 3 — Compute IWD
# ---------------------------------------------------------------------------

def step3_iwd(channel_mask, original_dem, burned_dem):
    print()
    print("=" * 60)
    print("Step 3 — Initial Water Depth (IWD)")
    print("=" * 60)
    print(f"  Method: IWD = BURN_DEPTH ({NORMAL_DEPTH} m) at channel cells, "
          "0 elsewhere")
    print("  (water fills the carved channel back to the original surface)")

    iwd = np.where(channel_mask > 0, NORMAL_DEPTH, 0.0)

    wet = iwd > 0
    print(f"  Wet cells : {int(np.sum(wet)):,}  "
          f"({100 * np.sum(wet) / iwd.size:.2f}%)")
    print(f"  IWD range : {iwd[wet].min():.2f} – {iwd[wet].max():.2f} m "
          f"(uniform)")

    return iwd


# ---------------------------------------------------------------------------
# Write outputs
# ---------------------------------------------------------------------------

def save_inputs(channel_mask, burned_dem, iwd, x, y):
    print()
    print("=" * 60)
    print("Saving v3 inputs")
    print("=" * 60)
    INPUT_DIR.mkdir(parents=True, exist_ok=True)

    write_rim2d_nc(channel_mask, x, y, INPUT_DIR / "channel_mask.nc")
    print("  Written: channel_mask.nc")

    write_rim2d_nc(burned_dem, x, y, INPUT_DIR / "dem.nc")
    print("  Written: dem.nc  (stream-burned)")

    write_rim2d_nc(iwd, x, y, INPUT_DIR / "iwd.nc")
    print("  Written: iwd.nc")

    # Copy unchanged rasters from v1
    copy_list = [
        "roughness.nc",
        "buildings.nc",
        "sealed_surface.nc",
        "pervious_surface.nc",
        "sewershed_v1_full.nc",
    ]
    for fname in copy_list:
        src = V1_INPUT / fname
        dst = INPUT_DIR / fname
        if src.exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied:  {fname}  (from v1/input)")
        else:
            print(f"  WARNING: {fname} not found in v1/input — skipped")


# ---------------------------------------------------------------------------
# Visualization
# ---------------------------------------------------------------------------

def visualize(channel_mask, original_dem, burned_dem, iwd, wc_int, x, y):
    print()
    print("Generating visualization...")
    VIS_DIR.mkdir(parents=True, exist_ok=True)

    x_km = (x - x[0]) / 1000.0
    y_km = (y - y[0]) / 1000.0
    ext  = [float(x_km[0]), float(x_km[-1]),
            float(y_km[0]), float(y_km[-1])]

    # Hillshade from original DEM
    from matplotlib.colors import LightSource
    ls = LightSource(azdeg=315, altdeg=45)
    hs = ls.hillshade(np.nan_to_num(original_dem, nan=0),
                      vert_exag=3, dx=30, dy=30)

    fig, axes = plt.subplots(2, 2, figsize=(18, 12))

    # --- Panel 1: WorldCover classes ---
    ax = axes[0, 0]
    wc_disp = np.where(wc_int > 0, wc_int, np.nan)
    cmap_wc = plt.cm.tab10
    im = ax.imshow(wc_disp, origin="lower",
                   extent=ext, cmap=cmap_wc,
                   vmin=10, vmax=100, interpolation="nearest")
    fig.colorbar(im, ax=ax, shrink=0.8, label="WorldCover class")
    ax.set_title("Step 1 — ESA WorldCover Classes\n"
                 f"Class 80 (perm. water) used for channel mask",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 2: Channel mask on hillshade ---
    ax = axes[0, 1]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.7)
    mask_disp = np.ma.masked_where(channel_mask == 0, channel_mask)
    ax.imshow(mask_disp, origin="lower", extent=ext,
              cmap=mcolors.ListedColormap(["#1a66ff"]),
              vmin=0.5, vmax=1.5, alpha=0.85, interpolation="nearest")
    n_ch = int(np.sum(channel_mask > 0))
    ax.set_title(f"Step 1 — Channel Mask  ({n_ch:,} cells, "
                 f"{100*n_ch/channel_mask.size:.2f}%)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 3: DEM difference (burn depth) ---
    ax = axes[1, 0]
    diff = original_dem - burned_dem
    diff_disp = np.ma.masked_where(diff <= 0, diff)
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.6)
    im3 = ax.imshow(diff_disp, origin="lower", extent=ext,
                    cmap="YlOrRd", vmin=0, vmax=BURN_DEPTH + 0.5,
                    alpha=0.85, interpolation="nearest")
    fig.colorbar(im3, ax=ax, shrink=0.8, label="Burn depth (m)")
    ax.set_title(f"Step 2 — Stream-Burned DEM  "
                 f"(BURN_DEPTH = {BURN_DEPTH} m)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 4: IWD ---
    ax = axes[1, 1]
    iwd_disp = np.ma.masked_where(iwd <= 0, iwd)
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.6)
    im4 = ax.imshow(iwd_disp, origin="lower", extent=ext,
                    cmap="Blues", vmin=0, vmax=NORMAL_DEPTH + 0.5,
                    alpha=0.85, interpolation="nearest")
    fig.colorbar(im4, ax=ax, shrink=0.8, label="IWD (m)")
    wet = int(np.sum(iwd > 0))
    ax.set_title(f"Step 3 — Initial Water Depth  "
                 f"({wet:,} wet cells, uniform {NORMAL_DEPTH} m)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    for ax in axes.flat:
        ax.xaxis.set_major_formatter(
            plt.FuncFormatter(lambda v, _: f"{v:.0f}"))
        ax.yaxis.set_major_formatter(
            plt.FuncFormatter(lambda v, _: f"{v:.0f}"))

    fig.suptitle(
        "Nairobi v3 — Stream-Burn IWD Method  "
        "(ESA WorldCover class 80 → channel mask → burned DEM → IWD)",
        fontsize=13, fontweight="bold"
    )
    fig.tight_layout()
    out = VIS_DIR / "v3_iwd_method.png"
    fig.savefig(str(out), dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Saved: {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Nairobi v3 — Stream-Burn IWD Setup")
    print(f"  BURN_DEPTH   = {BURN_DEPTH} m")
    print(f"  NORMAL_DEPTH = {NORMAL_DEPTH} m")
    print(f"  Water classes: {WATER_CLASSES} (ESA WorldCover)")
    print("=" * 60)

    # Step 1
    channel_mask, wc_int, x, y = step1_channel_mask()

    # Step 2
    original_dem, burned_dem, x, y = step2_burn_dem(channel_mask, x, y)

    # Step 3
    iwd = step3_iwd(channel_mask, original_dem, burned_dem)

    # Save
    save_inputs(channel_mask, burned_dem, iwd, x, y)

    # Visualize
    visualize(channel_mask, original_dem, burned_dem, iwd, wc_int, x, y)

    print()
    print("=" * 60)
    print("v3 setup complete.")
    print(f"  Inputs  : {INPUT_DIR}/")
    print(f"  Plots   : {VIS_DIR}/")
    print()
    print("Next steps:")
    print("  1. Inspect v3/visualizations/v3_iwd_method.png")
    print("  2. Copy v2 simulation def and update paths to v3")
    print("  3. Run RIM2D simulation from v3/")
    print("=" * 60)


if __name__ == "__main__":
    main()
