#!/usr/bin/env python3
"""
Setup script for v10 — Expanded domain culvert inflow simulation.

v10 changes:
  - Expanded domain: LAT 19.49-19.57, LON 33.25-33.36 (~385x295 cells)
  - 38-day simulation (Jul 25 – Aug 31, 2025)
  - Full-domain sewershed
  - Outputs to v10/ subdirectory

Downloads GEE data (Copernicus DEM, ESA WorldCover, GHSL, MERIT Hydro),
computes HND, burns river channel using satellite water mask, creates
roughness / buildings / sewershed, and writes simulation_v10.def.

Usage:
    micromamba run -n zarrv3 python setup_v10.py
"""

import json
import os
import shutil
import sys
import tempfile
import urllib.request
from pathlib import Path

import ee
import netCDF4
import numpy as np

from compute_hnd import compute_hand_from_dem
from regrid_xesmf import regrid_to_target

# ============================================================
# CONFIGURATION
# ============================================================

# Expanded domain bounding box (lat/lon)
BBOX = {"west": 33.25, "south": 19.49, "east": 33.36, "north": 19.57}

SCALE = 30  # meters
CRS = "EPSG:32636"  # UTM zone 36N

SA_KEY = (
    "/data/08-2023/working_notes_jupyter/ignore_nka_gitrepos/"
    "cno-e4drr/devops/earth-engine-service-account/keys/"
    "earthengine-sa-20260130-key.json"
)

WORK_DIR = Path("/data/rim2d/nile_highres")
V10_DIR = WORK_DIR / "v10"
INPUT_DIR = V10_DIR / "input"
OUTPUT_DIR = V10_DIR / "output"
TIF_DIR = V10_DIR / "tif"

# Simulation parameters
SIM_DUR = 3283200      # 38 days in seconds (Jul 25 – Aug 31)
TSTEP_IN = 1800        # 30-min boundary time step
N_RAIN = 1824          # 38 days * 48 half-hours
PLUVIAL_DT = 1800      # 30-min rainfall time step

# Native HND parameters
DRAIN_ACC_THRESH = 1000  # min upstream cells to classify as drainage

# Stream-burn parameters (satellite channel mask from ESA WorldCover)
BURN_DEPTH = 3.0       # meters — depth to lower DEM at water pixels
NORMAL_DEPTH = 3.0     # meters — IWD at channel cells

# Manning's n remap (ESA WorldCover class -> roughness)
MANNING_FROM = [10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 100]
MANNING_TO = [0.050, 0.040, 0.035, 0.035, 0.025, 0.030, 0.020, 0.025,
              0.040, 0.040, 0.030]

# MERIT Hydro native scale
MERIT_SCALE = 90  # meters
# GHSL native scale
GHSL_SCALE = 100  # meters


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def init_ee():
    """Initialize Earth Engine with service account."""
    with open(SA_KEY) as f:
        key_data = json.load(f)
    credentials = ee.ServiceAccountCredentials(key_data["client_email"], SA_KEY)
    ee.Initialize(credentials=credentials)
    print(f"EE initialized: {key_data['client_email']}")


def download_ee_tif(image, bbox_ee, path, scale=SCALE, crs=CRS):
    """Download an EE image as GeoTIFF projected to *crs* at *scale*."""
    url = image.getDownloadURL({
        "scale": scale,
        "region": bbox_ee,
        "format": "GEO_TIFF",
        "crs": crs,
    })
    with tempfile.NamedTemporaryFile(suffix=".tif", delete=False) as tmp:
        tmp_path = tmp.name
    try:
        urllib.request.urlretrieve(url, tmp_path)
        shutil.move(tmp_path, str(path))
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise
    print(f"  Downloaded: {path.name}")


def tif_to_rim2d_arrays(tif_path):
    """Read a GeoTIFF and return (data, x, y) in RIM2D convention."""
    import rasterio

    with rasterio.open(tif_path) as src:
        data = src.read(1).astype(np.float64)
        transform = src.transform
        nodata = src.nodata

    nrows, ncols = data.shape
    x = transform.c + transform.a * (np.arange(ncols) + 0.5)
    y_top = transform.f + transform.e * (np.arange(nrows) + 0.5)

    # Flip to y-ascending (south at index 0)
    y = y_top[::-1]
    data = data[::-1, :].copy()

    if nodata is not None:
        data[np.isclose(data, nodata)] = np.nan
    data[~np.isfinite(data)] = np.nan

    return data, x, y


def write_rim2d_nc(data, x, y, nc_path, fill_value=-9999.0):
    """Write a 2-D array to NetCDF3_CLASSIC matching RIM2D expectations."""
    arr = np.where(np.isnan(data), fill_value, data).astype(np.float32)
    nrows, ncols = arr.shape

    ds = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history = "Generated by setup_v10.py"

    ds.createDimension("x", ncols)
    ds.createDimension("y", nrows)

    xvar = ds.createVariable("x", "f8", ("x",))
    xvar[:] = x
    xvar.long_name = "x coordinate"
    xvar.units = "m"

    yvar = ds.createVariable("y", "f8", ("y",))
    yvar[:] = y
    yvar.long_name = "y coordinate"
    yvar.units = "m"

    band = ds.createVariable("Band1", "f4", ("y", "x"),
                             fill_value=np.float32(fill_value))
    band[:] = arr

    ds.close()


# ============================================================
# STEP 1 — Download from Google Earth Engine
# ============================================================

def step1_download_gee():
    """Download DEM, roughness, surface data and MERIT Hydro from GEE."""
    init_ee()

    bbox_ee = ee.Geometry.Rectangle(
        [BBOX["west"], BBOX["south"], BBOX["east"], BBOX["north"]]
    )
    TIF_DIR.mkdir(parents=True, exist_ok=True)

    # 1. DEM (Copernicus GLO-30)
    print("\n1. Downloading DEM (Copernicus GLO-30)...")
    dem = (ee.ImageCollection("COPERNICUS/DEM/GLO30")
           .filterBounds(bbox_ee)
           .select("DEM")
           .mosaic())
    download_ee_tif(dem, bbox_ee, TIF_DIR / "dem.tif")

    # 2. ESA WorldCover -> Manning's n roughness
    print("\n2. Downloading roughness (ESA WorldCover -> Manning's n)...")
    worldcover = ee.Image("ESA/WorldCover/v200/2021").select("Map")
    manning_int = [int(round(v * 1000)) for v in MANNING_TO]
    roughness = (worldcover
                 .remap(MANNING_FROM, manning_int)
                 .divide(1000)
                 .toFloat())
    download_ee_tif(roughness, bbox_ee, TIF_DIR / "roughness.tif")

    # 2b. Raw WorldCover classes (for satellite channel mask)
    print("\n2b. Downloading raw WorldCover classes...")
    worldcover_raw = ee.Image("ESA/WorldCover/v200/2021").select("Map")
    download_ee_tif(worldcover_raw, bbox_ee, TIF_DIR / "worldcover_classes.tif")

    # 3. GHSL Built-up Surface at native 100m
    print("\n3. Downloading surface data (GHSL at native 100m)...")
    ghsl = (ee.Image("JRC/GHSL/P2023A/GHS_BUILT_S/2020")
            .select("built_surface")
            .unmask(0))
    sealed = ghsl.divide(10000).clamp(0, 1).toFloat()
    pervious = ee.Image(1).subtract(sealed).toFloat()
    download_ee_tif(sealed, bbox_ee, TIF_DIR / "sealed_100m.tif",
                    scale=GHSL_SCALE)
    download_ee_tif(pervious, bbox_ee, TIF_DIR / "pervious_100m.tif",
                    scale=GHSL_SCALE)

    # 4. MERIT Hydro (elv, wth) at native 90m
    print("\n4. Downloading MERIT Hydro (elv, wth at native 90m)...")
    merit = ee.Image("MERIT/Hydro/v1_0_1")
    for band in ("elv", "wth"):
        download_ee_tif(merit.select(band), bbox_ee,
                        TIF_DIR / f"merit_{band}_90m.tif",
                        scale=MERIT_SCALE)

    print("\nAll GEE downloads complete.")


# ============================================================
# STEP 2 — Process data: compute HND, burn river, create NetCDF
# ============================================================

def step2_process_data():
    """Process GeoTIFFs into RIM2D-ready NetCDF inputs."""
    INPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ---- Read DEM ----
    print("\nReading DEM (Copernicus GLO-30)...")
    dem, x, y = tif_to_rim2d_arrays(TIF_DIR / "dem.tif")
    nrows, ncols = dem.shape
    dem_mask = np.isnan(dem)
    dx = abs(float(x[1] - x[0])) if ncols > 1 else SCALE
    print(f"  Grid: {ncols} x {nrows}, dx={dx:.1f}m")
    print(f"  DEM range: {np.nanmin(dem):.1f} - {np.nanmax(dem):.1f} m")

    # ---- Compute native 30m HND ----
    print("\nComputing native 30m HND from Copernicus DEM (pyflwdir)...")
    hnd, drain_mask, flwacc, dem_filled = compute_hand_from_dem(
        dem, nodata=-9999.0, drain_acc_thresh=DRAIN_ACC_THRESH, dx=dx
    )
    write_rim2d_nc(hnd, x, y, INPUT_DIR / "hnd_30m.nc")
    write_rim2d_nc(flwacc.astype(np.float64), x, y, INPUT_DIR / "flwacc_30m.nc")
    drain_float = np.where(drain_mask, 1.0, 0.0)
    write_rim2d_nc(drain_float, x, y, INPUT_DIR / "drainage_mask_30m.nc")
    print("  Written: hnd_30m.nc, flwacc_30m.nc, drainage_mask_30m.nc")

    # ---- Regrid MERIT elv (90m -> 30m) ----
    print("\nRegridding MERIT elv (90m -> 30m)...")
    merit_elv_raw, merit_x, merit_y = tif_to_rim2d_arrays(
        TIF_DIR / "merit_elv_90m.tif"
    )
    merit_elv = regrid_to_target(
        merit_elv_raw, merit_x, merit_y, x, y, method="bilinear"
    )
    valid_elv = merit_elv[np.isfinite(merit_elv)]
    print(f"  MERIT elv range: {valid_elv.min():.1f} - {valid_elv.max():.1f} m")

    # ---- Satellite channel mask (ESA WorldCover class 80) ----
    print("\nCreating channel mask from ESA WorldCover class 80...")
    wc_data, _, _ = tif_to_rim2d_arrays(TIF_DIR / "worldcover_classes.tif")
    if wc_data.shape != dem.shape:
        tmp = np.full(dem.shape, 0.0)
        h = min(wc_data.shape[0], nrows)
        w = min(wc_data.shape[1], ncols)
        tmp[:h, :w] = wc_data[:h, :w]
        wc_data = tmp
    channel_mask = (wc_data == 80).astype(np.float32)
    n_water = int(np.sum(channel_mask))
    print(f"  Water cells (class 80): {n_water} "
          f"({100 * n_water / dem.size:.1f}% of grid)")
    write_rim2d_nc(channel_mask, x, y, INPUT_DIR / "channel_mask.nc")

    # ---- Stream-burn DEM ----
    print(f"\nBurning river channel into DEM (burn_depth={BURN_DEPTH}m)...")
    burned_dem = dem.copy()
    burned_dem[channel_mask > 0] -= BURN_DEPTH
    write_rim2d_nc(burned_dem, x, y, INPUT_DIR / "dem.nc")
    print("  Written: dem.nc")

    # ---- IWD ----
    print(f"\nCreating IWD (channel mask, depth={NORMAL_DEPTH}m)...")
    iwd = np.where(channel_mask > 0, NORMAL_DEPTH, 0.0)
    write_rim2d_nc(iwd, x, y, INPUT_DIR / "iwd.nc")
    print("  Written: iwd.nc")

    # ---- Regrid GHSL sealed/pervious (100m -> 30m) ----
    print("\nRegridding GHSL sealed/pervious (100m -> 30m)...")
    for name, dest_name in [("sealed", "sealed_surface"),
                            ("pervious", "pervious_surface")]:
        src_data, src_x, src_y = tif_to_rim2d_arrays(
            TIF_DIR / f"{name}_100m.tif"
        )
        data_30m = regrid_to_target(
            src_data, src_x, src_y, x, y, method="bilinear"
        )
        data_30m = np.clip(np.nan_to_num(data_30m, nan=0.0), 0.0, 1.0)
        write_rim2d_nc(data_30m, x, y, INPUT_DIR / f"{dest_name}.nc")
        print(f"  Written: {dest_name}.nc")

    # ---- Roughness ----
    print("\nConverting roughness (already 30m)...")
    roughness, _, _ = tif_to_rim2d_arrays(TIF_DIR / "roughness.tif")
    if roughness.shape != dem.shape:
        tmp = np.full(dem.shape, np.nan)
        h = min(roughness.shape[0], nrows)
        w = min(roughness.shape[1], ncols)
        tmp[:h, :w] = roughness[:h, :w]
        roughness = tmp
    write_rim2d_nc(roughness, x, y, INPUT_DIR / "roughness.nc")
    print("  Written: roughness.nc")

    # ---- Buildings ----
    print("\nRasterizing Overture Maps building footprints...")
    from rasterize_buildings import rasterize_overture_buildings
    buildings = rasterize_overture_buildings(
        WORK_DIR / "buildings_overture.geojson",
        TIF_DIR / "dem.tif",
    )
    write_rim2d_nc(buildings, x, y, INPUT_DIR / "buildings.nc")
    n_bldg = int(np.sum(buildings > 0))
    print(f"  Building cells: {n_bldg} ({100 * n_bldg / buildings.size:.1f}%)")
    print("  Written: buildings.nc")

    # ---- Full-domain sewershed (all 1.0) ----
    print("\nCreating full-domain sewershed...")
    sewershed = np.ones_like(dem, dtype=np.float64)
    sewershed[dem_mask] = np.nan
    write_rim2d_nc(sewershed, x, y, INPUT_DIR / "sewershed_v10_full.nc")
    print("  Written: sewershed_v10_full.nc")

    # ---- Sealed surface: enhance at building cells ----
    print("\nEnhancing sealed surface at building locations...")
    sealed_data = regrid_to_target(
        *tif_to_rim2d_arrays(TIF_DIR / "sealed_100m.tif"), x, y,
        method="bilinear"
    )
    sealed_data = np.clip(np.nan_to_num(sealed_data, nan=0.0), 0.0, 1.0)
    sealed_data[buildings > 0] = 1.0
    write_rim2d_nc(sealed_data, x, y, INPUT_DIR / "sealed_surface.nc")
    print("  Written: sealed_surface.nc")

    return dem, burned_dem, iwd, channel_mask, x, y, dem_mask


# ============================================================
# STEP 3 — Create outflow / observation points file
# ============================================================

def step3_create_outflow():
    """Create empty outflowlocs.txt."""
    with open(INPUT_DIR / "outflowlocs.txt", "w") as f:
        f.write("0\n0\n")
    print("\nWritten: outflowlocs.txt (empty)")


# ============================================================
# STEP 4 — Write simulation_v10.def
# ============================================================

def step4_write_simdef():
    """Write the RIM2D flex-format simulation definition file."""
    ds = netCDF4.Dataset(str(INPUT_DIR / "dem.nc"))
    ncols = len(ds["x"][:])
    nrows = len(ds["y"][:])
    ds.close()

    rain_base = "imerg_v10_t"

    # Output every 6 hours for 38 days = 152 outputs
    n_outputs = SIM_DUR // 21600  # 3283200 / 21600 = 152
    out_times = [i * 21600 for i in range(1, n_outputs + 1)]
    out_timing_str = " ".join(str(t) for t in out_times)

    simdef = f"""\
# RIM2D model definition file (version 2.0)
# Nile high-resolution — v10 CULVERT INFLOW simulation
# Expanded domain with 2025 IMERG rainfall + 2 culvert inflow points
# Grid: {ncols} x {nrows}, cellsize ~30m

###### INPUT RASTERS ######
**DEM**
input/dem.nc
**buildings**
input/buildings.nc
**IWD**
file
input/iwd.nc
**roughness**
file
input/roughness.nc
**pervious_surface**
input/pervious_surface.nc
**sealed_surface**
input/sealed_surface.nc
**sewershed**
input/sewershed_v10_full.nc

###### BOUNDARIES ######
**fluvial_boundary**
input/inflowlocs_v10.txt

# RAINFALL — 2025 IMERG (actual, no amplification)
**pluvial_raster_nr**
{N_RAIN}
**pluvial_dt**
{PLUVIAL_DT}
**pluvial_start**
0
**pluvial_base_fn**
input/rain/{rain_base}

###### OUTPUT FILE SPECIFICATIONS ######
**output_base_fn**
output/nile_v10_
**out_cells**
input/outflowlocs.txt
**out_timing_nr**
{n_outputs}
**out_timing**
{out_timing_str}

###### MODEL PARAMETERS ######
**dt**
1
**sim_dur**
{SIM_DUR}
**inf_rate**
0
**sewer_cap**
0
**sewer_threshold**
0.002
**alpha**
0.4
**theta**
0.8

###### FLAGS ######
**verbose**
.TRUE.
**routing**
.TRUE.
**superverbose**
.FALSE.
**neg_wd_corr**
.TRUE.
**sew_sub**
.FALSE.
none
**fluv_bound**
.TRUE.
input/fluvbound_mask_v10.nc
**full_out**
.FALSE.
**closed_boundaries**
.FALSE.
**sheetflow_roughness**
.TRUE.

# end
"""

    defpath = V10_DIR / "simulation_v10.def"
    with open(str(defpath), "w") as f:
        f.write(simdef)
    print(f"\nWritten: {defpath.name} (grid {ncols}x{nrows})")


# ============================================================
# MAIN
# ============================================================

def main():
    V10_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("v10 — Expanded Domain Culvert Inflow Setup")
    print(f"  Domain: W={BBOX['west']}, S={BBOX['south']}, "
          f"E={BBOX['east']}, N={BBOX['north']}")
    print(f"  Scale: {SCALE}m, CRS: {CRS}")
    print(f"  Duration: {SIM_DUR/86400:.0f} days ({SIM_DUR}s)")
    print(f"  Rain files: {N_RAIN}")
    print("=" * 60)

    step1_download_gee()
    (dem, burned_dem, iwd, channel_mask,
     x, y, dem_mask) = step2_process_data()
    step3_create_outflow()
    step4_write_simdef()

    print("\n" + "=" * 60)
    print("v10 terrain setup complete!")
    print("Next steps:")
    print("  1. python download_imerg_v10.py       # download 2025 IMERG")
    print("  2. python run_v10_culvert_inflow.py    # generate culvert BCs")
    print("  3. python visualize_v10.py --inputs    # verify inputs")
    print("  4. cd v10 && ../../bin/RIM2D simulation_v10.def --def flex")
    print("=" * 60)


if __name__ == "__main__":
    main()
