#!/usr/bin/env python3
"""
Nairobi v4 — Steady-State Pre-Simulation IWD.

Generates realistic Initial Water Depth by running RIM2D with constant
low baseflow inflow at all CROSSING river entry points until the model
reaches steady state.  The final water depth output becomes iwd.nc for v4.

Method (from IWD_ATTEMPTS.md recommendation):
  The ideal approach is a pre-simulation steady-state run, as done for
  example_fluvial ('IWD162.5m.nc').  Nairobi terrain is steeply sloped
  (1440–2400 m), so gravity-driven steady state should converge in ~12 h.

Workflow:
  Step 1  Compute baseflow Q per CROSSING entry from catchment area
          using the FAO low-flow yield formula:
            Q_base = BASEFLOW_YIELD * UP_AREA (m³/s)
  Step 2  Convert Q_base → constant WSE using Manning's equation
            depth = (Q * n / (W * S^0.5))^(3/5),  WSE = bed_elev + depth
  Step 3  Write inflowlocs_v4ss.txt  (constant WSE, N+1 steps, 12 h run)
          Write fluvbound_mask_v4.nc (1-based index per entry cell)
          Write simulation_v4ss.def  (no rain, IWD=0, fluv_bound=TRUE)
  Step 4  Run RIM2D:
            cd v4 && ../../bin/RIM2D simulation_v4ss.def --def flex
  Step 5  Extract IWD from last water-depth output:
            python setup_v4.py --extract-iwd

Outputs in v4/:
  input/inflowlocs_v4ss.txt     steady-state inflow boundary conditions
  input/fluvbound_mask_v4.nc    fluvial boundary cell index mask
  simulation_v4ss.def           RIM2D definition file
  input/iwd.nc                  (after --extract-iwd) final water depth

Usage:
    cd /data/rim2d/nbo_2026
    # Step 1-3: generate inputs
    micromamba run -n zarrv3 python setup_v4.py
    # Step 4: run simulation
    cd v4 && export LD_LIBRARY_PATH=/data/rim2d/lib:$LD_LIBRARY_PATH
    ../../bin/RIM2D simulation_v4ss.def --def flex
    cd ..
    # Step 5: extract IWD
    micromamba run -n zarrv3 python setup_v4.py --extract-iwd
"""

import argparse
import shutil
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import netCDF4
import numpy as np
from pyproj import Transformer

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
WORK_DIR   = Path(__file__).resolve().parent
V1_INPUT   = WORK_DIR / "v1" / "input"
V4_DIR     = WORK_DIR / "v4"
INPUT_DIR  = V4_DIR / "input"
OUTPUT_DIR = V4_DIR / "output"
VIS_DIR    = V4_DIR / "visualizations"

ENTRIES_CSV = V1_INPUT / "river_entries_v1.csv"
DEM_PATH    = V1_INPUT / "dem.nc"

# ---------------------------------------------------------------------------
# Steady-state simulation parameters
# ---------------------------------------------------------------------------
SS_DUR_S    = 43200    # 12 h — enough for steep Nairobi terrain to equilibrate
SS_DT_S     = 1800     # 30 min WSE update interval
SS_N_STEPS  = SS_DUR_S // SS_DT_S    # 24 steps → 25 WSE values per cell

# Manning's channel geometry (consistent with v2)
MANNINGS_N  = 0.035
CHANNEL_W_BY_ORDER = {5: 25.0, 4: 15.0, 3: 8.0, 2: 4.0}   # m, wider for higher orders
CHANNEL_S   = 0.005   # bed slope (m/m) — Nairobi average

# Baseflow yield (m³/s per km²) — represents dry-season low flow
# FAO/GRDC global median for East Africa: ~0.5–2 L/s/km²
BASEFLOW_YIELD = 0.001   # 1 L/s/km² = 1e-3 m³/s/km²

# Catchment areas for CROSSING entries by stream order (km²)
# Same as v2 — anchored to HydroATLAS medians for Nairobi
UP_AREA_BY_ORDER = {5: 1500.0, 4: 375.0, 3: 95.0, 2: 24.0}

TO_UTM = Transformer.from_crs("EPSG:4326", "EPSG:32737", always_xy=True)

DPI = 150


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_nc(path):
    ds = netCDF4.Dataset(str(path))
    x  = np.array(ds["x"][:])
    y  = np.array(ds["y"][:])
    vn = [v for v in ds.variables if v not in ("x", "y")][0]
    data = np.array(ds[vn][:], dtype=np.float64)
    ds.close()
    data[data < -9000] = np.nan
    return data, x, y


def write_nc(data, x, y, path, varname="Band1"):
    fill = -9999.0
    arr  = np.where(np.isnan(data), fill, data).astype(np.float32)
    nrows, ncols = arr.shape
    ds = netCDF4.Dataset(str(path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history     = "Generated by setup_v4.py (Nairobi v4 steady-state IWD)"
    ds.createDimension("x", ncols)
    ds.createDimension("y", nrows)
    xv = ds.createVariable("x", "f8", ("x",))
    xv[:] = x
    xv.long_name = "x coordinate"
    xv.standard_name = "projection_x_coordinate"
    xv.units = "m"
    yv = ds.createVariable("y", "f8", ("y",))
    yv[:] = y
    yv.long_name = "y coordinate"
    yv.standard_name = "projection_y_coordinate"
    yv.units = "m"
    bv = ds.createVariable(varname, "f4", ("y", "x"),
                           fill_value=np.float32(fill))
    bv[:] = arr
    ds.close()


def grid_index(lon, lat, x_arr, y_arr):
    ex, ey = TO_UTM.transform(lon, lat)
    ix = int(np.argmin(np.abs(x_arr - ex)))
    iy = int(np.argmin(np.abs(y_arr - ey)))
    return (np.clip(ix, 0, len(x_arr) - 1),
            np.clip(iy, 0, len(y_arr) - 1))


def q_to_wse(q, bed_elev, stream_order):
    """Manning's wide rectangular channel → WSE."""
    w = CHANNEL_W_BY_ORDER.get(stream_order, 8.0)
    depth = (max(q, 1e-6) * MANNINGS_N / (w * CHANNEL_S**0.5)) ** (3.0 / 5.0)
    return bed_elev + depth


# ---------------------------------------------------------------------------
# Step 1+2: Baseflow Q and WSE for CROSSING entries
# ---------------------------------------------------------------------------

def compute_baseflow_entries(x_arr, y_arr, dem):
    """Load CROSSING entries and compute constant baseflow WSE."""
    import csv

    entries = []
    with open(str(ENTRIES_CSV)) as f:
        for row in csv.DictReader(f):
            if row["category"] == "crossing":
                entries.append({
                    "entry_id":    int(row["entry_id"]),
                    "stream_order": int(row["stream_order"]),
                    "lon":         float(row["lon"]),
                    "lat":         float(row["lat"]),
                    "linkno":      int(row["linkno"]),
                })

    print(f"  CROSSING entries: {len(entries)}")
    print(f"  {'ID':>4}  {'Order':>5}  {'Area km²':>9}  "
          f"{'Q_base m³/s':>12}  {'Depth m':>8}  {'WSE m':>10}")
    print("  " + "-" * 56)

    for e in entries:
        so    = e["stream_order"]
        area  = UP_AREA_BY_ORDER.get(so, 24.0)
        q     = BASEFLOW_YIELD * area          # m³/s
        ix, iy = grid_index(e["lon"], e["lat"], x_arr, y_arr)
        bed   = float(dem[iy, ix]) if np.isfinite(dem[iy, ix]) else 1600.0
        wse   = q_to_wse(q, bed, so)
        depth = wse - bed
        e.update({"area_km2": area, "q_base": q, "bed_elev": bed,
                  "wse": wse, "depth": depth, "ix": ix, "iy": iy})
        print(f"  {e['entry_id']:>4}  {so:>5}  {area:>9.0f}  "
              f"{q:>12.3f}  {depth:>8.3f}  {wse:>10.3f}")

    return entries


# ---------------------------------------------------------------------------
# Step 3a: Write inflowlocs
# ---------------------------------------------------------------------------

def write_inflowlocs(entries):
    """
    RIM2D inflowlocs format (flex, confirmed from readin_flex.f90):
      Line 1: sim_dur_s
      Line 2: dt_s
      Line 3: n_cells
      Each cell: iy1  ix1  wse_0  wse_1  ...  wse_N   (N+1 values)
    WSE is constant throughout — this is a steady-state forcing.
    """
    path = INPUT_DIR / "inflowlocs_v4ss.txt"
    n = len(entries)
    lines = [str(SS_DUR_S), str(SS_DT_S), str(n)]

    for e in entries:
        iy1 = e["iy"] + 1   # 1-based
        ix1 = e["ix"] + 1
        # N+1 values: prepend bed_elev at t=0 (dry start), then constant WSE
        wse_vals = [e["bed_elev"]] + [e["wse"]] * SS_N_STEPS
        wse_str  = "\t".join(f"{w:.4f}" for w in wse_vals)
        lines.append(f"{iy1}\t{ix1}\t{wse_str}")

    with open(str(path), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Written: {path.name}  "
          f"({n} entries × {SS_N_STEPS} steps + t=0)")
    return path


# ---------------------------------------------------------------------------
# Step 3b: Write fluvbound_mask
# ---------------------------------------------------------------------------

def write_fluvbound_mask(entries, x_arr, y_arr, dem):
    """1-based index per entry cell; RIM2D uses maxval(mask) = n_entries."""
    mask = np.zeros_like(dem, dtype=np.float32)
    for i, e in enumerate(entries):
        mask[e["iy"], e["ix"]] = float(i + 1)
    path = INPUT_DIR / "fluvbound_mask_v4.nc"
    write_nc(mask, x_arr, y_arr, path)
    print(f"  Written: fluvbound_mask_v4.nc  "
          f"({int((mask > 0).sum())} cells, max={int(mask.max())})")


# ---------------------------------------------------------------------------
# Step 3c: Write RIM2D def file
# ---------------------------------------------------------------------------

def write_def(n_entries):
    def_path = V4_DIR / "simulation_v4ss.def"
    # Output every 1800s (30 min), 24 snapshots
    out_times = " ".join(str(t) for t in range(SS_DT_S, SS_DUR_S + SS_DT_S, SS_DT_S))

    def_text = f"""\
# RIM2D definition file — Nairobi v4 Steady-State pre-run
# Purpose: generate realistic IWD for the v4 event simulation
# After run: use last water-depth output as iwd.nc

**DEM**
../v1/input/dem.nc

**buildings**
../v1/input/buildings.nc

**IWD**
homo
0.0

**roughness**
file
../v1/input/roughness.nc

**pervious_surface**
../v1/input/pervious_surface.nc

**sealed_surface**
../v1/input/sealed_surface.nc

**sewershed**
../v1/input/sewershed_v1_full.nc

**pluvial_raster_nr**
0

**pluvial_dt**
1

**pluvial_start**
0

**pluvial_base_fn**
none

**output_base_fn**
output/nbo_v4ss_

**out_timing_nr**
{SS_N_STEPS}

**out_timing**
{out_times}

**out_cells**
input/outflowlocs_v4.txt

**dt**
1.0

**sim_dur**
{SS_DUR_S}

**inf_rate**
0

**sewer_cap**
0

**sewer_threshold**
0.002

**alpha**
0.5

**theta**
0.8

**verbose**
.FALSE.

**superverbose**
.FALSE.

**routing**
.TRUE.

**fluvial_boundary**
input/inflowlocs_v4ss.txt

**fluv_bound**
.TRUE.
input/fluvbound_mask_v4.nc
"""
    with open(str(def_path), "w") as f:
        f.write(def_text)
    print(f"  Written: {def_path.name}")
    return def_path


def write_dummy_outflowlocs():
    """RIM2D requires out_cells file; write a minimal 1-cell placeholder."""
    path = INPUT_DIR / "outflowlocs_v4.txt"
    # Format: noutloc / outtstep / iy ix name (1-based)
    path.write_text("1\n1800\n1 1 dummy\n")
    print(f"  Written: {path.name}  (placeholder)")


# ---------------------------------------------------------------------------
# Step 5: Extract IWD from last steady-state output
# ---------------------------------------------------------------------------

def extract_iwd():
    import glob, os, re

    VIS_DIR.mkdir(parents=True, exist_ok=True)

    all_wd = glob.glob(str(OUTPUT_DIR / "nbo_v4ss_wd_*.nc"))
    wd_files = sorted(
        [f for f in all_wd
         if re.search(r"nbo_v4ss_wd_\d+\.nc$", os.path.basename(f))],
        key=lambda p: int(re.search(r"nbo_v4ss_wd_(\d+)\.nc",
                                     os.path.basename(p)).group(1))
    )
    if not wd_files:
        print("ERROR: No water depth output files found in v4/output/")
        print("       Run the simulation first.")
        return

    last_file = wd_files[-1]
    t_sec = int(re.search(r"nbo_v4ss_wd_(\d+)\.nc",
                           os.path.basename(last_file)).group(1))
    print(f"  Using last output: {os.path.basename(last_file)}  "
          f"(t = {t_sec}s = {t_sec/3600:.1f}h)")

    wd, x_arr, y_arr = load_nc(last_file)

    # Cap unrealistic boundary artefacts
    wd = np.where(wd > 20, 0.0, wd)
    wd = np.where(wd < 0,  0.0, wd)

    wet = wd > 0.01
    print(f"  Wet cells  : {int(np.sum(wet)):,}  "
          f"({100 * np.sum(wet) / wd.size:.2f}%)")
    print(f"  Depth range: {float(wd[wet].min()):.3f} – "
          f"{float(wd[wet].max()):.3f} m")
    print(f"  Mean depth : {float(wd[wet].mean()):.3f} m")

    iwd_path = INPUT_DIR / "iwd.nc"
    write_nc(wd, x_arr, y_arr, iwd_path)
    print(f"  Written: {iwd_path}")

    # Copy all other rasters from v1 (if not already done)
    copy_list = [
        "channel_mask.nc", "roughness.nc", "buildings.nc",
        "sealed_surface.nc", "pervious_surface.nc", "sewershed_v1_full.nc",
    ]
    for fname in copy_list:
        src = V1_INPUT / fname
        dst = INPUT_DIR / fname
        if src.exists() and not dst.exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied:  {fname}  (from v1/input)")

    # Visualize IWD
    visualize_iwd(wd, x_arr, y_arr, t_sec)

    print("\nv4 IWD extraction complete.")
    print("  Next: create event simulation def pointing to v4/input/iwd.nc")


def visualize_iwd(wd, x_arr, y_arr, t_sec):
    """4-panel verification of the extracted steady-state IWD."""
    dem, _, _ = load_nc(DEM_PATH)
    buildings, _, _ = load_nc(V1_INPUT / "buildings.nc")
    buildings = np.flipud(buildings)

    from matplotlib.colors import LightSource
    ls = LightSource(azdeg=315, altdeg=45)
    hs = ls.hillshade(np.nan_to_num(dem, nan=0), vert_exag=3, dx=30, dy=30)

    ext_m = [float(x_arr[0]), float(x_arr[-1]),
             float(y_arr[0]), float(y_arr[-1])]

    fig, axes = plt.subplots(1, 3, figsize=(22, 8))

    # --- Panel 1: IWD depth map ---
    ax = axes[0]
    ax.imshow(hs, origin="lower", extent=ext_m, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.6)
    wd_m = np.ma.masked_where(wd < 0.01, wd)
    im = ax.imshow(wd_m, origin="lower", extent=ext_m,
                   cmap="Blues", vmin=0, vmax=3.0,
                   interpolation="nearest", alpha=0.85)
    fig.colorbar(im, ax=ax, shrink=0.75, label="Water depth (m)")
    wet = wd > 0.01
    ax.set_title(
        f"v4 Steady-State IWD  (t={t_sec/3600:.0f}h)\n"
        f"Wet cells: {int(np.sum(wet)):,} ({100*np.sum(wet)/wd.size:.2f}%)",
        fontsize=11, fontweight="bold"
    )
    ax.set_xlabel("Easting (m UTM 37S)")
    ax.set_ylabel("Northing (m UTM 37S)")

    # --- Panel 2: depth histogram ---
    ax = axes[1]
    vals = wd[wet]
    ax.hist(vals, bins=50, color="#1a66ff", alpha=0.8, edgecolor="white")
    ax.axvline(float(np.median(vals)), color="red", lw=1.5,
               label=f"Median: {float(np.median(vals)):.2f} m")
    ax.axvline(float(np.mean(vals)), color="orange", lw=1.5, linestyle="--",
               label=f"Mean: {float(np.mean(vals)):.2f} m")
    ax.set_xlabel("Water depth (m)")
    ax.set_ylabel("Cell count")
    ax.set_title("IWD depth distribution\n(wet cells only)",
                 fontsize=11, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

    # --- Panel 3: IWD + buildings overlay ---
    ax = axes[2]
    ax.imshow(hs, origin="lower", extent=ext_m, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.6)
    ax.imshow(wd_m, origin="lower", extent=ext_m,
              cmap="Blues", vmin=0, vmax=3.0,
              interpolation="nearest", alpha=0.85)
    bldg = buildings > 0
    if np.any(bldg):
        ax.contour(bldg.astype(float), levels=[0.5],
                   origin="lower", extent=ext_m,
                   colors=["#ff8800"], linewidths=0.5, alpha=0.6)
    ax.set_title("IWD + buildings (orange)\n"
                 "Steady-state river channels",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("Easting (m UTM 37S)")

    for ax in axes:
        ax.xaxis.set_major_formatter(
            plt.FuncFormatter(lambda v, _: f"{v/1000:.0f}"))
        ax.yaxis.set_major_formatter(
            plt.FuncFormatter(lambda v, _: f"{v/1000:.0f}"))

    fig.suptitle(
        "Nairobi v4 — Steady-State IWD from RIM2D Pre-Simulation\n"
        f"12h constant baseflow, 16 CROSSING entry points",
        fontsize=13, fontweight="bold"
    )
    fig.tight_layout()
    out = VIS_DIR / "v4_steadystate_iwd.png"
    fig.savefig(str(out), dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Saved: {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

wd_files_used = []   # populated in extract_iwd, used by visualize_iwd title

def main():
    global wd_files_used

    parser = argparse.ArgumentParser()
    parser.add_argument("--extract-iwd", action="store_true",
                        help="Extract IWD from last SS output (run after simulation)")
    args = parser.parse_args()

    if args.extract_iwd:
        print("=" * 60)
        print("Nairobi v4 — Extract IWD from steady-state output")
        print("=" * 60)
        INPUT_DIR.mkdir(parents=True, exist_ok=True)
        extract_iwd()
        return

    # ---- Generate inputs ----
    print("=" * 60)
    print("Nairobi v4 — Steady-State IWD Setup")
    print(f"  SS duration  : {SS_DUR_S}s ({SS_DUR_S/3600:.0f}h)")
    print(f"  SS time step : {SS_DT_S}s ({SS_DT_S/60:.0f} min)")
    print(f"  WSE steps/cell: {SS_N_STEPS + 1}  (incl. t=0 dry start)")
    print(f"  Baseflow yield: {BASEFLOW_YIELD*1000:.1f} L/s/km²")
    print("=" * 60)

    INPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    VIS_DIR.mkdir(parents=True, exist_ok=True)

    dem, x_arr, y_arr = load_nc(DEM_PATH)
    print(f"\nLoaded DEM: {dem.shape[1]}×{dem.shape[0]} cells  "
          f"({(x_arr[-1]-x_arr[0])/1000:.1f}×{(y_arr[-1]-y_arr[0])/1000:.1f} km)")

    print("\nStep 1+2 — Baseflow Q and WSE per CROSSING entry:")
    entries = compute_baseflow_entries(x_arr, y_arr, dem)
    wd_files_used = entries

    print("\nStep 3 — Writing simulation inputs:")
    write_inflowlocs(entries)
    write_fluvbound_mask(entries, x_arr, y_arr, dem)
    write_dummy_outflowlocs()
    write_def(len(entries))

    print("\n" + "=" * 60)
    print("Setup complete.  Next:")
    print()
    print("  # Run the steady-state simulation:")
    print("  cd /data/rim2d/nbo_2026/v4")
    print("  export LD_LIBRARY_PATH=/data/rim2d/lib:$LD_LIBRARY_PATH")
    print("  ../../bin/RIM2D simulation_v4ss.def --def flex")
    print()
    print("  # Extract IWD from final output:")
    print("  cd /data/rim2d/nbo_2026")
    print("  micromamba run -n zarrv3 python setup_v4.py --extract-iwd")
    print("=" * 60)


if __name__ == "__main__":
    main()
