#!/usr/bin/env python3
"""
Nairobi v5 — TDX-Hydro river network burn IWD.

Uses the pre-downloaded TDX-Hydro v2 river network
(river_network_tdx_v2.geojson, 141 segments, orders 2–5) instead of
HydroRIVERS, and assigns width + depth by stream order using standard
tropical-river hydraulic scaling.

  Step 1 — Load TDX-Hydro river network (orders 2–5)
  Step 2 — Assign width + depth by stream order
  Step 3 — Burn DEM: buffer each segment by rivwth/2, lower by rivdph
  Step 4 — IWD = original DEM - burned DEM (clipped to ≥ 0)
  Step 5 — Write v5/input/ + visualization

Stream-order width/depth table (Nairobi tropical rivers):
  Order 2 — W= 15m, D=0.5m   (headwater streams)
  Order 3 — W= 30m, D=1.0m
  Order 4 — W= 60m, D=1.5m
  Order 5 — W=120m, D=2.5m   (Nairobi / Athi R.)

Inputs (all pre-existing):
  v1/tif/dem.tif                    — 30m Copernicus DEM
  v1/input/river_network_tdx_v2.geojson — TDX-Hydro river network

Outputs → v5/input/
  dem.nc, iwd.nc, channel_mask.nc
  roughness.nc (from v3b Dynamic World), + buildings, sealed, pervious, sewershed

Usage:
    cd /data/rim2d/nbo_2026
    micromamba run -n hydromt-wflow python setup_v5.py
"""

import shutil
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import netCDF4
import numpy as np
import geopandas as gpd
import rasterio
from rasterio.features import rasterize as rio_rasterize
from rasterio.transform import from_bounds
from rasterio.warp import reproject, Resampling
from shapely.ops import linemerge, unary_union
from shapely.geometry import mapping

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BBOX = {"west": 36.6, "south": -1.402004, "east": 37.1, "north": -1.098036}

WORK_DIR  = Path(__file__).resolve().parent
V1_TIF    = WORK_DIR / "v1" / "tif"
V1_INPUT  = WORK_DIR / "v1" / "input"
V3B_INPUT = WORK_DIR / "v3b" / "input"
V5_DIR    = WORK_DIR / "v5"
INPUT_DIR = V5_DIR / "input"
VIS_DIR   = V5_DIR / "visualizations"

TDX_RIVER_PATH = V1_INPUT / "river_network_tdx_v2.geojson"

# Width and depth by stream order (Nairobi tropical rivers)
# Order 2: headwater streams, Order 5: Nairobi/Athi main stem
ORDER_WIDTH = {2: 15,  3: 30,  4: 60,  5: 120}   # metres
ORDER_DEPTH = {2: 0.5, 3: 1.0, 4: 1.5, 5:  2.5}  # metres

DPI = 150

# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def tif_to_rim2d_arrays(tif_path):
    with rasterio.open(str(tif_path)) as src:
        data      = src.read(1).astype(np.float64)
        transform = src.transform
        nodata    = src.nodata
        crs       = src.crs
    nrows, ncols = data.shape
    x     = transform.c + transform.a * (np.arange(ncols) + 0.5)
    y_top = transform.f + transform.e * (np.arange(nrows) + 0.5)
    y     = y_top[::-1]
    data  = data[::-1, :].copy()
    if nodata is not None:
        data[np.isclose(data, nodata)] = np.nan
    data[~np.isfinite(data)] = np.nan
    return data, x, y, transform, crs


def load_nc(path):
    ds = netCDF4.Dataset(str(path))
    x = np.array(ds["x"][:])
    y = np.array(ds["y"][:])
    varname = [v for v in ds.variables if v not in ("x", "y")][0]
    data = np.array(ds[varname][:], dtype=np.float64)
    ds.close()
    data[data < -9000] = np.nan
    return data, x, y


def write_rim2d_nc(data, x, y, nc_path, varname="Band1"):
    fill = -9999.0
    arr  = np.where(np.isnan(data), fill, data).astype(np.float32)
    ds = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history     = "Generated by setup_v5.py (Nairobi v5)"
    ds.createDimension("x", arr.shape[1])
    ds.createDimension("y", arr.shape[0])
    xv = ds.createVariable("x", "f8", ("x",)); xv[:] = x
    xv.long_name = "x coordinate"; xv.standard_name = "projection_x_coordinate"; xv.units = "m"
    yv = ds.createVariable("y", "f8", ("y",)); yv[:] = y
    yv.long_name = "y coordinate"; yv.standard_name = "projection_y_coordinate"; yv.units = "m"
    bv = ds.createVariable(varname, "f4", ("y", "x"), fill_value=np.float32(fill))
    bv[:] = arr
    ds.close()


def regrid_to_dem(src_tif, ref_transform, ref_crs, ref_shape, method=Resampling.bilinear):
    """Reproject src_tif to match DEM grid. Returns y-ascending array."""
    dst_height, dst_width = ref_shape
    with rasterio.open(src_tif) as src:
        src_data = src.read(1).astype(np.float64)
        dst_data = np.zeros((dst_height, dst_width), dtype=np.float64)
        reproject(
            source=src_data, destination=dst_data,
            src_transform=src.transform, src_crs=src.crs,
            dst_transform=ref_transform, dst_crs=ref_crs,
            resampling=method,
        )
    dst_data = dst_data[::-1, :].copy()
    dst_data[~np.isfinite(dst_data)] = np.nan
    return dst_data


# ---------------------------------------------------------------------------
# Step 1 — Load TDX-Hydro river network
# ---------------------------------------------------------------------------

def step1_load_rivers(target_crs):
    print("=" * 60)
    print("Step 1 — Load TDX-Hydro v2 river network")
    print("=" * 60)

    gdf = gpd.read_file(str(TDX_RIVER_PATH))
    gdf = gdf.to_crs(target_crs)

    print(f"  Segments loaded : {len(gdf)}")
    for order in sorted(gdf["stream_order"].unique()):
        n = (gdf["stream_order"] == order).sum()
        w = ORDER_WIDTH.get(int(order), 15)
        d = ORDER_DEPTH.get(int(order), 0.5)
        print(f"  Order {order} : {n:3d} segments  →  W={w}m, D={d}m")

    return gdf


# ---------------------------------------------------------------------------
# Steps 2+3 — Assign width and depth by stream order
# ---------------------------------------------------------------------------

def step2_assign_width_depth(gdf):
    print()
    print("=" * 60)
    print("Steps 2+3 — Assign width & depth by stream order")
    print("=" * 60)

    gdf["rivwth"] = gdf["stream_order"].map(
        lambda o: ORDER_WIDTH.get(int(o), 15)
    ).astype(float)
    gdf["rivdph"] = gdf["stream_order"].map(
        lambda o: ORDER_DEPTH.get(int(o), 0.5)
    ).astype(float)

    print(f"  Width  range : {gdf['rivwth'].min():.0f} – {gdf['rivwth'].max():.0f} m")
    print(f"  Depth  range : {gdf['rivdph'].min():.2f} – {gdf['rivdph'].max():.2f} m")
    return gdf


def step3_estimate_depth(gdf):
    # Combined into step2 — kept as pass-through for API compatibility
    return gdf


# ---------------------------------------------------------------------------
# Step 4 — Burn DEM
# ---------------------------------------------------------------------------

def step4_burn_dem(gdf, dem, x, y, ref_transform, ref_crs):
    print()
    print("=" * 60)
    print("Step 4 — Burn river channels into DEM")
    print("=" * 60)

    nrows, ncols = dem.shape
    burned_dem   = dem.copy()
    depth_raster = np.zeros_like(dem)

    # Build rasterio transform in y-ascending convention for rasterize
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    # rasterio uses top-left corner, y-descending
    ras_transform = rasterio.transform.from_origin(
        x[0] - dx / 2,
        y[-1] + dy / 2,   # top of domain
        dx, dy
    )

    burned_count = 0
    for _, row in gdf.iterrows():
        geom  = row.geometry
        w     = float(row["rivwth"])
        d     = float(row["rivdph"])

        if geom.is_empty:
            continue

        # Buffer the centerline by half-width
        buf = geom.buffer(w / 2.0)

        # Rasterize buffer → mask (y-descending for rasterio)
        mask = rio_rasterize(
            [(mapping(buf), 1)],
            out_shape=(nrows, ncols),
            transform=ras_transform,
            fill=0,
            dtype=np.uint8,
        )
        # Flip to y-ascending (match our arrays)
        mask = mask[::-1, :]

        cells = mask > 0
        if not cells.any():
            continue

        # Lower DEM by depth, track max depth per cell
        burned_dem[cells]   = np.minimum(burned_dem[cells], dem[cells] - d)
        depth_raster[cells] = np.maximum(depth_raster[cells], d)
        burned_count += int(cells.sum())

    # IWD = original - burned, clipped to ≥ 0
    iwd = np.maximum(dem - burned_dem, 0.0)
    iwd[~np.isfinite(iwd)] = 0.0

    wet = iwd > 0
    print(f"  Rivers burned      : {len(gdf)}")
    print(f"  Total cells burned : {int(wet.sum()):,}  "
          f"({100 * wet.sum() / dem.size:.2f}% of domain)")
    print(f"  IWD range          : {iwd[wet].min():.2f} – {iwd[wet].max():.2f} m")
    print(f"  Burned DEM min     : {np.nanmin(burned_dem):.1f} m")

    channel_mask = wet.astype(np.float64)
    return burned_dem, iwd, channel_mask


# ---------------------------------------------------------------------------
# Step 5 — Save outputs
# ---------------------------------------------------------------------------

def step5_save(burned_dem, iwd, channel_mask, x, y):
    print()
    print("=" * 60)
    print("Step 5 — Save v5 inputs")
    print("=" * 60)
    INPUT_DIR.mkdir(parents=True, exist_ok=True)

    write_rim2d_nc(burned_dem,    x, y, INPUT_DIR / "dem.nc")
    print("  Written: dem.nc  (stream-burned)")
    write_rim2d_nc(iwd,           x, y, INPUT_DIR / "iwd.nc")
    print("  Written: iwd.nc")
    write_rim2d_nc(channel_mask,  x, y, INPUT_DIR / "channel_mask.nc")
    print("  Written: channel_mask.nc")

    # Use v3b roughness (Dynamic World) if available, else v1
    roughness_src = V3B_INPUT / "roughness.nc"
    if not roughness_src.exists():
        roughness_src = V1_INPUT / "roughness.nc"
        print("  NOTE: v3b roughness not found, using v1 WorldCover roughness")

    copy_list = {
        "roughness.nc":        roughness_src,
        "buildings.nc":        V1_INPUT / "buildings.nc",
        "sealed_surface.nc":   V1_INPUT / "sealed_surface.nc",
        "pervious_surface.nc": V1_INPUT / "pervious_surface.nc",
        "sewershed_v1_full.nc":V1_INPUT / "sewershed_v1_full.nc",
    }
    for fname, src in copy_list.items():
        dst = INPUT_DIR / fname
        if src.exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied:  {fname}")
        else:
            print(f"  WARNING: {fname} not found at {src}")


# ---------------------------------------------------------------------------
# Step 6 — Visualization
# ---------------------------------------------------------------------------

def step6_visualize(gdf, dem, burned_dem, iwd, x, y):
    print()
    print("=" * 60)
    print("Step 6 — Visualization")
    print("=" * 60)
    VIS_DIR.mkdir(parents=True, exist_ok=True)

    from matplotlib.colors import LightSource
    ls = LightSource(azdeg=315, altdeg=45)
    hs = ls.hillshade(np.nan_to_num(dem, nan=0), vert_exag=3, dx=30, dy=30)

    x_km = (x - x[0]) / 1000.0
    y_km = (y - y[0]) / 1000.0
    ext  = [float(x_km[0]), float(x_km[-1]),
            float(y_km[0]), float(y_km[-1])]

    fig, axes = plt.subplots(1, 3, figsize=(22, 8))

    # --- Panel 1: TDX river network coloured by stream order ---
    ax = axes[0]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.7)
    order_colors = {2: "#74b9ff", 3: "#0984e3", 4: "#6c5ce7", 5: "#d63031"}
    order_lw     = {2: 0.6, 3: 1.2, 4: 2.0, 5: 3.0}
    import matplotlib.patches as mpatches
    handles = []
    for order in sorted(order_colors):
        sub = gdf[gdf["stream_order"] == order]
        for _, row in sub.iterrows():
            geom = row.geometry
            if geom.is_empty:
                continue
            segs = [geom] if geom.geom_type == "LineString" else list(geom.geoms)
            for seg in segs:
                xs_g = [(xv - x[0]) / 1000 for xv in seg.xy[0]]
                ys_g = [(yv - y[0]) / 1000 for yv in seg.xy[1]]
                ax.plot(xs_g, ys_g, color=order_colors[order],
                        lw=order_lw[order], alpha=0.9)
        w = ORDER_WIDTH[order]; d = ORDER_DEPTH[order]
        handles.append(mpatches.Patch(color=order_colors[order],
            label=f"Order {order} — W={w}m, D={d}m ({len(sub)} segs)"))
    ax.legend(handles=handles, loc="lower right", fontsize=8, framealpha=0.9)
    ax.set_title(f"TDX-Hydro v2 River Network ({len(gdf)} segments)\n"
                 "coloured by stream order",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 2: Burn depth (DEM diff) ---
    ax = axes[1]
    diff = np.maximum(dem - burned_dem, 0)
    diff_disp = np.ma.masked_where(diff <= 0, diff)
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    im2 = ax.imshow(diff_disp, origin="lower", extent=ext,
                    cmap="YlOrRd", vmin=0, vmax=diff[diff > 0].max() if diff.any() else 5,
                    alpha=0.85, interpolation="nearest")
    fig.colorbar(im2, ax=ax, shrink=0.7, label="Burn depth (m)")
    n_burned = int((diff > 0).sum())
    ax.set_title(f"Stream-Burned DEM\n({n_burned:,} cells burned, "
                 f"max burn {diff.max():.1f} m)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 3: IWD ---
    ax = axes[2]
    iwd_disp = np.ma.masked_where(iwd <= 0, iwd)
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    im3 = ax.imshow(iwd_disp, origin="lower", extent=ext,
                    cmap="Blues", vmin=0, vmax=iwd[iwd > 0].max() if (iwd > 0).any() else 5,
                    alpha=0.85, interpolation="nearest")
    fig.colorbar(im3, ax=ax, shrink=0.7, label="IWD (m)")
    wet = int((iwd > 0).sum())
    ax.set_title(f"Initial Water Depth (v5)\n({wet:,} wet cells, "
                 f"mean {iwd[iwd > 0].mean():.2f} m)",
                 fontsize=11, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    for ax in axes:
        ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0f}"))
        ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0f}"))

    fig.suptitle(
        "Nairobi v5 — TDX-Hydro River Burn IWD\n"
        f"Width/depth by stream order  (orders 2–5)",
        fontsize=13, fontweight="bold"
    )
    fig.tight_layout()
    out = VIS_DIR / "v5_hydrorivers_burn_iwd.png"
    fig.savefig(str(out), dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Saved: {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Nairobi v5 — TDX-Hydro River Burn IWD")
    print(f"  Domain  : {BBOX}")
    print(f"  Orders  : {ORDER_WIDTH}")
    print("=" * 60)

    # Load DEM
    print("\nLoading DEM...")
    dem, x, y, ref_transform, ref_crs = tif_to_rim2d_arrays(V1_TIF / "dem.tif")
    print(f"  DEM shape : {dem.shape}  CRS: {ref_crs}")
    print(f"  DEM range : {np.nanmin(dem):.1f} – {np.nanmax(dem):.1f} m")

    # Step 1 — rivers
    gdf = step1_load_rivers(ref_crs)

    # Steps 2+3 — assign width & depth by stream order
    gdf = step2_assign_width_depth(gdf)
    gdf = step3_estimate_depth(gdf)

    # Step 4 — burn
    burned_dem, iwd, channel_mask = step4_burn_dem(
        gdf, dem, x, y, ref_transform, ref_crs
    )

    # Step 5 — save
    step5_save(burned_dem, iwd, channel_mask, x, y)

    # Step 6 — visualize
    step6_visualize(gdf, dem, burned_dem, iwd, x, y)

    print()
    print("=" * 60)
    print("v5 setup complete.")
    print(f"  Inputs : {INPUT_DIR}/")
    print(f"  Plots  : {VIS_DIR}/")
    print()
    print("Improvement over v3:")
    print("  v3 — uniform 3m burn at WorldCover water pixels")
    print("  v5 — geometry burn: width/depth by TDX stream order")
    print()
    print("Next steps:")
    print("  1. Inspect v5/visualizations/v5_hydrorivers_burn_iwd.png")
    print("  2. Create simulation_v5ss.def for steady-state pre-run")
    print("  3. Run RIM2D from v5/")
    print("=" * 60)


if __name__ == "__main__":
    main()
