#!/usr/bin/env python3
"""
Nairobi v6 — Combined MERIT HND + TDX-Hydro IWD.

Merges the two complementary methods:

  Layer A — TDX-Hydro geometry burn (from v5)
            River segments orders 2–5, width/depth by stream order.
            Buffer each centerline by rivwth/2, lower DEM by rivdph.
            Orders 3–5 get full geometry; order 2 gets narrow/shallow burn.

  Layer B — MERIT HND drainage fill (from v1 approach)
            Cells where HND = 0 (sitting exactly on a drainage line)
            that are NOT already covered by a TDX channel footprint.
            Applied with a small headwater burn depth (HND_BURN_DEPTH).

Priority rule: TDX footprint always wins — HND fill only applied in gaps.

Result:
  - Physically correct width/depth on 141 mapped TDX channels
  - Continuous drainage connectivity via HND=0 headwater cells
  - No double-counting between layers

Parameters:
  ORDER_WIDTH  = {2:15, 3:30, 4:60, 5:120}  m
  ORDER_DEPTH  = {2:0.5, 3:1.0, 4:1.5, 5:2.5}  m
  HND_BURN_DEPTH = 0.3 m  (headwater channel seed depth)

Outputs → v6/input/
  dem.nc, iwd.nc, channel_mask.nc
  roughness.nc (from v3b), + buildings, sealed, pervious, sewershed

Usage:
    cd /data/rim2d/nbo_2026
    micromamba run -n hydromt-wflow python setup_v6.py
"""

import shutil
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
import netCDF4
import numpy as np
import geopandas as gpd
import rasterio
from rasterio.features import rasterize as rio_rasterize
from rasterio.warp import reproject, Resampling
from shapely.ops import linemerge
from shapely.geometry import mapping

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

WORK_DIR  = Path(__file__).resolve().parent
V1_TIF    = WORK_DIR / "v1" / "tif"
V1_INPUT  = WORK_DIR / "v1" / "input"
V3B_INPUT = WORK_DIR / "v3b" / "input"
V6_DIR    = WORK_DIR / "v6"
INPUT_DIR = V6_DIR / "input"
VIS_DIR   = V6_DIR / "visualizations"

TDX_RIVER_PATH = V1_INPUT / "river_network_tdx_v2.geojson"
HND_PATH       = V1_INPUT / "hnd_30m.nc"

# TDX width/depth by stream order
ORDER_WIDTH = {2: 15,  3: 30,  4: 60,  5: 120}   # metres
ORDER_DEPTH = {2: 0.5, 3: 1.0, 4: 1.5, 5:  2.5}  # metres

# HND headwater burn depth (layer B gap-fill)
HND_BURN_DEPTH = 0.3   # m

DPI = 150

# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def tif_to_rim2d_arrays(tif_path):
    with rasterio.open(str(tif_path)) as src:
        data      = src.read(1).astype(np.float64)
        transform = src.transform
        nodata    = src.nodata
        crs       = src.crs
    nrows, ncols = data.shape
    x     = transform.c + transform.a * (np.arange(ncols) + 0.5)
    y_top = transform.f + transform.e * (np.arange(nrows) + 0.5)
    y     = y_top[::-1]
    data  = data[::-1, :].copy()
    if nodata is not None:
        data[np.isclose(data, nodata)] = np.nan
    data[~np.isfinite(data)] = np.nan
    return data, x, y, transform, crs


def load_nc(path):
    ds = netCDF4.Dataset(str(path))
    x = np.array(ds["x"][:])
    y = np.array(ds["y"][:])
    var = [v for v in ds.variables if v not in ("x", "y")][0]
    data = np.array(ds[var][:], dtype=np.float64)
    ds.close()
    data[data < -9000] = np.nan
    return data, x, y


def write_rim2d_nc(data, x, y, nc_path, varname="Band1"):
    fill = -9999.0
    arr  = np.where(np.isnan(data), fill, data).astype(np.float32)
    ds = netCDF4.Dataset(str(nc_path), "w", format="NETCDF3_CLASSIC")
    ds.Conventions = "CF-1.5"
    ds.history     = "Generated by setup_v6.py (Nairobi v6)"
    ds.createDimension("x", arr.shape[1])
    ds.createDimension("y", arr.shape[0])
    xv = ds.createVariable("x", "f8", ("x",)); xv[:] = x
    xv.long_name = "x coordinate"; xv.standard_name = "projection_x_coordinate"; xv.units = "m"
    yv = ds.createVariable("y", "f8", ("y",)); yv[:] = y
    yv.long_name = "y coordinate"; yv.standard_name = "projection_y_coordinate"; yv.units = "m"
    bv = ds.createVariable(varname, "f4", ("y", "x"), fill_value=np.float32(fill))
    bv[:] = arr
    ds.close()


# ---------------------------------------------------------------------------
# Step 1 — Layer A: TDX-Hydro geometry burn
# ---------------------------------------------------------------------------

def step1_tdx_burn(dem, x, y, ref_crs):
    print("=" * 60)
    print("Step 1 — Layer A: TDX-Hydro geometry burn")
    print("=" * 60)

    gdf = gpd.read_file(str(TDX_RIVER_PATH)).to_crs(ref_crs)
    gdf["rivwth"] = gdf["stream_order"].map(lambda o: float(ORDER_WIDTH.get(int(o), 15)))
    gdf["rivdph"] = gdf["stream_order"].map(lambda o: float(ORDER_DEPTH.get(int(o), 0.5)))

    for order in sorted(gdf["stream_order"].unique()):
        n = (gdf["stream_order"] == order).sum()
        print(f"  Order {order}: {n:3d} segments  "
              f"W={ORDER_WIDTH[int(order)]}m  D={ORDER_DEPTH[int(order)]}m")

    nrows, ncols = dem.shape
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    ras_transform = rasterio.transform.from_origin(
        x[0] - dx / 2,
        y[-1] + dy / 2,
        dx, dy
    )

    tdx_footprint = np.zeros((nrows, ncols), dtype=bool)
    depth_layer_a = np.zeros((nrows, ncols), dtype=np.float64)

    for _, row in gdf.iterrows():
        geom = row.geometry
        w    = float(row["rivwth"])
        d    = float(row["rivdph"])
        if geom.is_empty:
            continue
        buf  = geom.buffer(w / 2.0)
        mask = rio_rasterize(
            [(mapping(buf), 1)],
            out_shape=(nrows, ncols),
            transform=ras_transform,
            fill=0, dtype=np.uint8,
        )[::-1, :]   # flip to y-ascending
        cells = mask > 0
        tdx_footprint[cells] = True
        depth_layer_a[cells] = np.maximum(depth_layer_a[cells], d)

    n_tdx = int(tdx_footprint.sum())
    print(f"\n  TDX footprint cells : {n_tdx:,}  "
          f"({100 * n_tdx / dem.size:.2f}%)")
    print(f"  Depth range (A)     : {depth_layer_a[tdx_footprint].min():.2f} – "
          f"{depth_layer_a[tdx_footprint].max():.2f} m")

    return tdx_footprint, depth_layer_a


# ---------------------------------------------------------------------------
# Step 2 — Layer B: MERIT HND gap-fill
# ---------------------------------------------------------------------------

def step2_hnd_fill(dem, x, y, tdx_footprint):
    print()
    print("=" * 60)
    print("Step 2 — Layer B: MERIT HND headwater gap-fill")
    print(f"  HND = 0 cells, outside TDX footprint → burn {HND_BURN_DEPTH}m")
    print("=" * 60)

    hnd, hnd_x, hnd_y = load_nc(HND_PATH)

    # HND is on same 30m grid (from v1 setup) — verify shape match
    if hnd.shape != dem.shape:
        raise RuntimeError(
            f"HND shape {hnd.shape} != DEM shape {dem.shape}. "
            "Re-run setup_v1.py to regenerate hnd_30m.nc on the correct grid."
        )

    # Drainage cells: HND == 0 (exactly on drainage line)
    hnd_drain = (hnd == 0.0)

    # Gap-fill: HND drainage cells NOT covered by TDX
    gap_cells = hnd_drain & ~tdx_footprint

    n_hnd   = int(hnd_drain.sum())
    n_gap   = int(gap_cells.sum())
    n_tdx   = int(tdx_footprint.sum())
    n_overlap = int((hnd_drain & tdx_footprint).sum())

    print(f"  HND=0 cells total   : {n_hnd:,}")
    print(f"  Already in TDX      : {n_overlap:,}")
    print(f"  Gap-fill (layer B)  : {n_gap:,}  "
          f"({100 * n_gap / dem.size:.2f}%)")

    depth_layer_b = np.where(gap_cells, HND_BURN_DEPTH, 0.0)
    return gap_cells, depth_layer_b


# ---------------------------------------------------------------------------
# Step 3 — Merge layers, burn DEM, compute IWD
# ---------------------------------------------------------------------------

def step3_merge_and_burn(dem, tdx_footprint, depth_layer_a,
                          gap_cells, depth_layer_b):
    print()
    print("=" * 60)
    print("Step 3 — Merge layers A + B, burn DEM")
    print("=" * 60)

    # Combined depth: A takes priority, B fills gaps
    combined_depth = np.zeros_like(dem)
    combined_depth[tdx_footprint] = depth_layer_a[tdx_footprint]
    combined_depth[gap_cells]     = depth_layer_b[gap_cells]

    channel_mask = (combined_depth > 0).astype(np.float64)
    burned_dem   = dem.copy()
    burned_dem[channel_mask > 0] -= combined_depth[channel_mask > 0]

    iwd = np.maximum(dem - burned_dem, 0.0)
    iwd[~np.isfinite(iwd)] = 0.0

    wet = iwd > 0
    n_a   = int(tdx_footprint.sum())
    n_b   = int(gap_cells.sum())
    print(f"  Layer A (TDX)       : {n_a:,} cells")
    print(f"  Layer B (HND gap)   : {n_b:,} cells")
    print(f"  Total wet cells     : {wet.sum():,}  "
          f"({100 * wet.sum() / dem.size:.2f}%)")
    print(f"  IWD range           : {iwd[wet].min():.2f} – {iwd[wet].max():.2f} m")
    print(f"  Burned DEM min      : {np.nanmin(burned_dem):.1f} m")

    return burned_dem, iwd, channel_mask, combined_depth


# ---------------------------------------------------------------------------
# Step 4 — Save outputs
# ---------------------------------------------------------------------------

def step4_save(burned_dem, iwd, channel_mask, x, y):
    print()
    print("=" * 60)
    print("Step 4 — Save v6 inputs")
    print("=" * 60)
    INPUT_DIR.mkdir(parents=True, exist_ok=True)

    write_rim2d_nc(burned_dem,   x, y, INPUT_DIR / "dem.nc")
    print("  Written: dem.nc")
    write_rim2d_nc(iwd,          x, y, INPUT_DIR / "iwd.nc")
    print("  Written: iwd.nc")
    write_rim2d_nc(channel_mask, x, y, INPUT_DIR / "channel_mask.nc")
    print("  Written: channel_mask.nc")

    roughness_src = V3B_INPUT / "roughness.nc"
    if not roughness_src.exists():
        roughness_src = V1_INPUT / "roughness.nc"
        print("  NOTE: v3b roughness not found, using v1")

    for fname, src in {
        "roughness.nc":         roughness_src,
        "buildings.nc":         V1_INPUT / "buildings.nc",
        "sealed_surface.nc":    V1_INPUT / "sealed_surface.nc",
        "pervious_surface.nc":  V1_INPUT / "pervious_surface.nc",
        "sewershed_v1_full.nc": V1_INPUT / "sewershed_v1_full.nc",
    }.items():
        dst = INPUT_DIR / fname
        if Path(src).exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied:  {fname}")
        else:
            print(f"  WARNING: {fname} not found")


# ---------------------------------------------------------------------------
# Step 5 — Visualization
# ---------------------------------------------------------------------------

def step5_visualize(dem, burned_dem, iwd, combined_depth,
                    tdx_footprint, gap_cells, x, y):
    print()
    print("=" * 60)
    print("Step 5 — Visualization")
    print("=" * 60)
    VIS_DIR.mkdir(parents=True, exist_ok=True)

    from matplotlib.colors import LightSource
    ls = LightSource(azdeg=315, altdeg=45)
    hs = ls.hillshade(np.nan_to_num(dem, nan=0), vert_exag=3, dx=30, dy=30)

    x_km = (x - x[0]) / 1000.0
    y_km = (y - y[0]) / 1000.0
    ext  = [float(x_km[0]), float(x_km[-1]),
            float(y_km[0]), float(y_km[-1])]

    # Load v5 IWD for comparison
    v5_iwd, _, _ = load_nc(WORK_DIR / "v5" / "input" / "iwd.nc")
    v5_iwd = np.where(v5_iwd < 0, 0, v5_iwd)

    fig, axes = plt.subplots(2, 3, figsize=(22, 14))

    cmap_iwd = plt.cm.Blues
    vmax_iwd = 3.0

    # --- Panel 1: Layer A (TDX) ---
    ax = axes[0, 0]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    layer_a_disp = np.ma.masked_where(~tdx_footprint, combined_depth)
    ax.imshow(layer_a_disp, origin="lower", extent=ext,
              cmap=cmap_iwd, vmin=0, vmax=vmax_iwd,
              alpha=0.85, interpolation="nearest")
    ax.set_title(f"Layer A — TDX-Hydro geometry\n"
                 f"({tdx_footprint.sum():,} cells, D=0.5–2.5m by order)",
                 fontsize=10, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 2: Layer B (HND gap-fill) ---
    ax = axes[0, 1]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    layer_b_disp = np.ma.masked_where(~gap_cells,
                                       np.full_like(dem, HND_BURN_DEPTH))
    ax.imshow(layer_b_disp, origin="lower", extent=ext,
              cmap=plt.cm.Oranges, vmin=0, vmax=1.0,
              alpha=0.80, interpolation="nearest")
    ax.set_title(f"Layer B — MERIT HND gap-fill\n"
                 f"({gap_cells.sum():,} cells, D={HND_BURN_DEPTH}m uniform)",
                 fontsize=10, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 3: Combined v6 IWD ---
    ax = axes[0, 2]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    iwd_disp = np.ma.masked_where(iwd <= 0, iwd)
    im3 = ax.imshow(iwd_disp, origin="lower", extent=ext,
                    cmap=cmap_iwd, vmin=0, vmax=vmax_iwd,
                    alpha=0.88, interpolation="nearest")
    fig.colorbar(im3, ax=ax, shrink=0.8, label="IWD (m)")
    wet = iwd > 0
    ax.set_title(f"v6 Combined IWD\n"
                 f"({wet.sum():,} cells, mean={iwd[wet].mean():.2f}m, "
                 f"max={iwd[wet].max():.2f}m)",
                 fontsize=10, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 4: Layer contribution map ---
    ax = axes[1, 0]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.55)
    contrib = np.zeros((*dem.shape, 4), dtype=np.float32)
    contrib[tdx_footprint] = [0.10, 0.52, 0.90, 0.80]   # blue = TDX
    contrib[gap_cells]     = [0.90, 0.45, 0.10, 0.70]   # orange = HND gap
    ax.imshow(contrib, origin="lower", extent=ext, zorder=5)
    handles = [
        mpatches.Patch(color="#1a85e5", label=f"TDX geometry ({tdx_footprint.sum():,})"),
        mpatches.Patch(color="#e57320", label=f"HND gap-fill ({gap_cells.sum():,})"),
    ]
    ax.legend(handles=handles, loc="lower right", fontsize=9, framealpha=0.9)
    ax.set_title("Layer contribution\nBlue=TDX  Orange=HND gap-fill",
                 fontsize=10, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 5: v5 vs v6 difference ---
    ax = axes[1, 1]
    ax.imshow(hs, origin="lower", extent=ext, cmap="gray",
              vmin=0.3, vmax=1.0, alpha=0.45)
    diff = iwd - v5_iwd
    diff_disp = np.ma.masked_where((iwd == 0) & (v5_iwd == 0), diff)
    im5 = ax.imshow(diff_disp, origin="lower", extent=ext,
                    cmap=plt.cm.RdBu_r, vmin=-2.0, vmax=2.0,
                    alpha=0.85, interpolation="nearest")
    fig.colorbar(im5, ax=ax, shrink=0.8, label="Δ IWD (m)")
    new_cells = int(((iwd > 0) & (v5_iwd == 0)).sum())
    ax.set_title(f"v6 − v5 difference\n"
                 f"New cells from HND: {new_cells:,}",
                 fontsize=10, fontweight="bold")
    ax.set_xlabel("x (km)"); ax.set_ylabel("y (km)")

    # --- Panel 6: Depth histogram comparison ---
    ax = axes[1, 2]
    for label, arr, color in [
        ("v5 TDX only",    v5_iwd, "#0984e3"),
        ("v6 combined",    iwd,    "#00b894"),
    ]:
        vals = arr[arr > 0].flatten()
        ax.hist(vals, bins=40, alpha=0.6, color=color, density=True,
                label=f"{label}  (n={len(vals):,}, μ={vals.mean():.2f}m)")
    ax.axvline(HND_BURN_DEPTH, color="#e17055", ls="--", lw=1.2,
               label=f"HND burn depth ({HND_BURN_DEPTH}m)")
    ax.set_xlabel("IWD (m)")
    ax.set_ylabel("Density")
    ax.set_title("Depth distribution: v5 vs v6",
                 fontsize=10, fontweight="bold")
    ax.legend(fontsize=9, framealpha=0.9)

    for ax in axes.flat:
        if hasattr(ax, 'xaxis'):
            ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0f}"))
            ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.0f}"))

    fig.suptitle(
        "Nairobi v6 — Combined TDX-Hydro + MERIT HND IWD\n"
        f"Layer A: TDX geometry (orders 2–5)  ·  "
        f"Layer B: HND gap-fill ({HND_BURN_DEPTH}m headwaters)",
        fontsize=13, fontweight="bold"
    )
    fig.tight_layout()
    out = VIS_DIR / "v6_combined_iwd.png"
    fig.savefig(str(out), dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"  Saved: {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Nairobi v6 — Combined TDX-Hydro + MERIT HND IWD")
    print(f"  TDX widths  : {ORDER_WIDTH}")
    print(f"  TDX depths  : {ORDER_DEPTH}")
    print(f"  HND burn    : {HND_BURN_DEPTH} m (gap-fill only)")
    print("=" * 60)

    print("\nLoading DEM...")
    dem, x, y, ref_transform, ref_crs = tif_to_rim2d_arrays(V1_TIF / "dem.tif")
    print(f"  Shape: {dem.shape}  CRS: {ref_crs}")
    print(f"  Range: {np.nanmin(dem):.1f} – {np.nanmax(dem):.1f} m")

    # Layer A — TDX geometry burn
    tdx_footprint, depth_layer_a = step1_tdx_burn(dem, x, y, ref_crs)

    # Layer B — HND gap-fill
    gap_cells, depth_layer_b = step2_hnd_fill(dem, x, y, tdx_footprint)

    # Merge + burn
    burned_dem, iwd, channel_mask, combined_depth = step3_merge_and_burn(
        dem, tdx_footprint, depth_layer_a, gap_cells, depth_layer_b
    )

    # Save
    step4_save(burned_dem, iwd, channel_mask, x, y)

    # Visualize
    step5_visualize(dem, burned_dem, iwd, combined_depth,
                    tdx_footprint, gap_cells, x, y)

    print()
    print("=" * 60)
    print("v6 setup complete.")
    print(f"  Inputs : {INPUT_DIR}/")
    print(f"  Plots  : {VIS_DIR}/")
    print()
    print("Layer breakdown:")
    print(f"  A (TDX)      : {tdx_footprint.sum():,} cells  0.5–2.5m depth")
    print(f"  B (HND gaps) : {gap_cells.sum():,} cells  {HND_BURN_DEPTH}m depth")
    print(f"  Total        : {int(tdx_footprint.sum() + gap_cells.sum()):,} cells")
    print()
    print("Next: create simulation_v6ss.def and run steady-state")
    print("=" * 60)


if __name__ == "__main__":
    main()
